//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/LoginMessage.proto
namespace com.maple.common.login.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetUnusedUsernameRequest")]
  public partial class GetUnusedUsernameRequest : global::ProtoBuf.IExtensible
  {
    public GetUnusedUsernameRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetUnusedUsernameResponse")]
  public partial class GetUnusedUsernameResponse : global::ProtoBuf.IExtensible
  {
    public GetUnusedUsernameResponse() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonRegisterRequest")]
  public partial class CommonRegisterRequest : global::ProtoBuf.IExtensible
  {
    public CommonRegisterRequest() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonRegisterResponse")]
  public partial class CommonRegisterResponse : global::ProtoBuf.IExtensible
  {
    public CommonRegisterResponse() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonInviteRegisterRequest")]
  public partial class CommonInviteRegisterRequest : global::ProtoBuf.IExtensible
  {
    public CommonInviteRegisterRequest() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private long _inviteCode = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"inviteCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long inviteCode
    {
      get { return _inviteCode; }
      set { _inviteCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginSuccessResponse")]
  public partial class LoginSuccessResponse : global::ProtoBuf.IExtensible
  {
    public LoginSuccessResponse() {}
    
    private string _onlineToken = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"onlineToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string onlineToken
    {
      get { return _onlineToken; }
      set { _onlineToken = value; }
    }
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _headIndex = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"headIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headIndex
    {
      get { return _headIndex; }
      set { _headIndex = value; }
    }
    private string _headUrl = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"headUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headUrl
    {
      get { return _headUrl; }
      set { _headUrl = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _code = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private int _roomIndex = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"roomIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomIndex
    {
      get { return _roomIndex; }
      set { _roomIndex = value; }
    }
    private bool _isConnect = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isConnect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isConnect
    {
      get { return _isConnect; }
      set { _isConnect = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OnlineTokenLoginRequest")]
  public partial class OnlineTokenLoginRequest : global::ProtoBuf.IExtensible
  {
    public OnlineTokenLoginRequest() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _onlineToken = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"onlineToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string onlineToken
    {
      get { return _onlineToken; }
      set { _onlineToken = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonLoginRequest")]
  public partial class CommonLoginRequest : global::ProtoBuf.IExtensible
  {
    public CommonLoginRequest() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private bool _exitRoomFlag = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"exitRoomFlag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool exitRoomFlag
    {
      get { return _exitRoomFlag; }
      set { _exitRoomFlag = value; }
    }
    private bool _isConnect = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isConnect", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isConnect
    {
      get { return _isConnect; }
      set { _isConnect = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TouristLoginRequest")]
  public partial class TouristLoginRequest : global::ProtoBuf.IExtensible
  {
    public TouristLoginRequest() {}
    
    private string _touristCode = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"touristCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string touristCode
    {
      get { return _touristCode; }
      set { _touristCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TouristLoginResponse")]
  public partial class TouristLoginResponse : global::ProtoBuf.IExtensible
  {
    public TouristLoginResponse() {}
    
    private string _touristCode = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"touristCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string touristCode
    {
      get { return _touristCode; }
      set { _touristCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangePasswordRequest")]
  public partial class ChangePasswordRequest : global::ProtoBuf.IExtensible
  {
    public ChangePasswordRequest() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _oldPassword = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"oldPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string oldPassword
    {
      get { return _oldPassword; }
      set { _oldPassword = value; }
    }
    private string _newPassword = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"newPassword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string newPassword
    {
      get { return _newPassword; }
      set { _newPassword = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangePasswordResponse")]
  public partial class ChangePasswordResponse : global::ProtoBuf.IExtensible
  {
    public ChangePasswordResponse() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogoutResponse")]
  public partial class LogoutResponse : global::ProtoBuf.IExtensible
  {
    public LogoutResponse() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CommonNameLoginRequest")]
  public partial class CommonNameLoginRequest : global::ProtoBuf.IExtensible
  {
    public CommonNameLoginRequest() {}
    
    private string _username = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WxLoginCodeRequest")]
  public partial class WxLoginCodeRequest : global::ProtoBuf.IExtensible
  {
    public WxLoginCodeRequest() {}
    
    private string _code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WxLoginCodeResponse")]
  public partial class WxLoginCodeResponse : global::ProtoBuf.IExtensible
  {
    public WxLoginCodeResponse() {}
    
    private string _refreshToken = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"refreshToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string refreshToken
    {
      get { return _refreshToken; }
      set { _refreshToken = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WxLoginRequest")]
  public partial class WxLoginRequest : global::ProtoBuf.IExtensible
  {
    public WxLoginRequest() {}
    
    private string _refreshToken = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"refreshToken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string refreshToken
    {
      get { return _refreshToken; }
      set { _refreshToken = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WxLoginReAuthResponse")]
  public partial class WxLoginReAuthResponse : global::ProtoBuf.IExtensible
  {
    public WxLoginReAuthResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"LoginMsgCode")]
    public enum LoginMsgCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_GET_UNUSED_USERNAME_REQUEST", Value=268435969)]
      C_S_GET_UNUSED_USERNAME_REQUEST = 268435969,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_GET_UNUSED_USERNAME_RESPONSE", Value=536871425)]
      S_C_GET_UNUSED_USERNAME_RESPONSE = 536871425,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_COMMON_REGISTER_REQUEST", Value=268435970)]
      C_S_COMMON_REGISTER_REQUEST = 268435970,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_COMMON_REGISTER_RESPONSE", Value=536871426)]
      S_C_COMMON_REGISTER_RESPONSE = 536871426,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_COMMON_INVITE_REGISTER_REQUEST", Value=268435971)]
      C_S_COMMON_INVITE_REGISTER_REQUEST = 268435971,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_COMMON_NAME_LOGIN_REQUEST", Value=268435972)]
      C_S_COMMON_NAME_LOGIN_REQUEST = 268435972,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_WX_LOGIN_CODE_REQUEST", Value=268435973)]
      C_S_WX_LOGIN_CODE_REQUEST = 268435973,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_WX_LOGIN_CODE_RESPONSE", Value=536871429)]
      S_C_WX_LOGIN_CODE_RESPONSE = 536871429,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_WX_LOGIN_REQUEST", Value=268435974)]
      C_S_WX_LOGIN_REQUEST = 268435974,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_WX_LOGIN_REAUTH_RESPONSE", Value=536871430)]
      S_C_WX_LOGIN_REAUTH_RESPONSE = 536871430,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_LOGIN_SUCCESS_RESPONSE", Value=536871440)]
      S_C_LOGIN_SUCCESS_RESPONSE = 536871440,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_ONLINE_TOKEN_LOGIN_REQUEST", Value=268435985)]
      C_S_ONLINE_TOKEN_LOGIN_REQUEST = 268435985,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_COMMON_LOGIN_REQUEST", Value=268435986)]
      C_S_COMMON_LOGIN_REQUEST = 268435986,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_TOURIST_LOGIN_REQUEST", Value=268435987)]
      C_S_TOURIST_LOGIN_REQUEST = 268435987,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TOURIST_LOGIN_RESPONSE", Value=536871443)]
      S_C_TOURIST_LOGIN_RESPONSE = 536871443,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_CHANGE_PASSWORD_REQUEST", Value=268436001)]
      C_S_CHANGE_PASSWORD_REQUEST = 268436001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_CHANGE_PASSWORD_RESPONSE", Value=536871457)]
      S_C_CHANGE_PASSWORD_RESPONSE = 536871457,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_LOGOUT_RESPONSE", Value=536871473)]
      S_C_LOGOUT_RESPONSE = 536871473
    }
  
}