//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/NetworkMessage.proto
namespace com.maple.network.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignOutRequest")]
  public partial class SignOutRequest : global::ProtoBuf.IExtensible
  {
    public SignOutRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignOutResponse")]
  public partial class SignOutResponse : global::ProtoBuf.IExtensible
  {
    public SignOutResponse() {}
    
    private int _code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PingRequest")]
  public partial class PingRequest : global::ProtoBuf.IExtensible
  {
    public PingRequest() {}
    
    private long _pingTime = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pingTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long pingTime
    {
      get { return _pingTime; }
      set { _pingTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PingResponse")]
  public partial class PingResponse : global::ProtoBuf.IExtensible
  {
    public PingResponse() {}
    
    private long _pingTime = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pingTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long pingTime
    {
      get { return _pingTime; }
      set { _pingTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeartBeatRequest")]
  public partial class HeartBeatRequest : global::ProtoBuf.IExtensible
  {
    public HeartBeatRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeartBeatResponse")]
  public partial class HeartBeatResponse : global::ProtoBuf.IExtensible
  {
    public HeartBeatResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HintMessageResponse")]
  public partial class HintMessageResponse : global::ProtoBuf.IExtensible
  {
    public HintMessageResponse() {}
    
    private string _content = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetConnectTokenRequest")]
  public partial class GetConnectTokenRequest : global::ProtoBuf.IExtensible
  {
    public GetConnectTokenRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetConnectTokenResponse")]
  public partial class GetConnectTokenResponse : global::ProtoBuf.IExtensible
  {
    public GetConnectTokenResponse() {}
    
    private int _token = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InvalidTokenResponse")]
  public partial class InvalidTokenResponse : global::ProtoBuf.IExtensible
  {
    public InvalidTokenResponse() {}
    
    private int _token = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"NetworkMsgCode")]
    public enum NetworkMsgCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_PING_REQUEST", Value=268435456)]
      C_S_PING_REQUEST = 268435456,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_PING_RESPONSE", Value=536870912)]
      S_C_PING_RESPONSE = 536870912,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_HEART_BEAT_REQUEST", Value=268435457)]
      C_S_HEART_BEAT_REQUEST = 268435457,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_HEART_BEAT_RESPONSE", Value=536870913)]
      S_C_HEART_BEAT_RESPONSE = 536870913,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_HINT_MESSAGE_RESPONSE", Value=536870914)]
      S_C_HINT_MESSAGE_RESPONSE = 536870914,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_GET_CONNECT_TOKEN_REQUEST", Value=268435713)]
      C_S_GET_CONNECT_TOKEN_REQUEST = 268435713,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_GET_CONNECT_TOKEN_RESPONSE", Value=536871169)]
      S_C_GET_CONNECT_TOKEN_RESPONSE = 536871169,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_INVALID_TOKEN_RESPONSE", Value=536871170)]
      S_C_INVALID_TOKEN_RESPONSE = 536871170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_SIGN_OUT_REQUEST", Value=268435715)]
      C_S_SIGN_OUT_REQUEST = 268435715,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_SIGN_OUT_RESPONSE", Value=536871171)]
      S_C_SIGN_OUT_RESPONSE = 536871171
    }
  
}