//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/OseeTwoEightMessage.proto
// Note: requires additional types generated from: proto/OseeTwoEightPublicData.proto
namespace com.maple.game.osee.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TERoomReconnectRequest")]
  public partial class TERoomReconnectRequest : global::ProtoBuf.IExtensible
  {
    public TERoomReconnectRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TERoomCancelBankerRequest")]
  public partial class TERoomCancelBankerRequest : global::ProtoBuf.IExtensible
  {
    public TERoomCancelBankerRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TERoomCancelBankerResponse")]
  public partial class TERoomCancelBankerResponse : global::ProtoBuf.IExtensible
  {
    public TERoomCancelBankerResponse() {}
    
    private int _isSuccess = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isSuccess", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isSuccess
    {
      get { return _isSuccess; }
      set { _isSuccess = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TwoEightJoinRoomRequest")]
  public partial class TwoEightJoinRoomRequest : global::ProtoBuf.IExtensible
  {
    public TwoEightJoinRoomRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TERoomQuitRequest")]
  public partial class TERoomQuitRequest : global::ProtoBuf.IExtensible
  {
    public TERoomQuitRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TERoomQuitResponse")]
  public partial class TERoomQuitResponse : global::ProtoBuf.IExtensible
  {
    public TERoomQuitResponse() {}
    
    private int _isSuccess = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isSuccess", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int isSuccess
    {
      get { return _isSuccess; }
      set { _isSuccess = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TERoomStateResponse")]
  public partial class TERoomStateResponse : global::ProtoBuf.IExtensible
  {
    public TERoomStateResponse() {}
    
    private int _roomState = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomState
    {
      get { return _roomState; }
      set { _roomState = value; }
    }
    private int _remainTime = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"remainTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int remainTime
    {
      get { return _remainTime; }
      set { _remainTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TwoEightRoomInfoResponse")]
  public partial class TwoEightRoomInfoResponse : global::ProtoBuf.IExtensible
  {
    public TwoEightRoomInfoResponse() {}
    
    private int _roomCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private long _bankerId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bankerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bankerId
    {
      get { return _bankerId; }
      set { _bankerId = value; }
    }
    private int _roomState = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomState
    {
      get { return _roomState; }
      set { _roomState = value; }
    }
    private long _shunMoney = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"shunMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long shunMoney
    {
      get { return _shunMoney; }
      set { _shunMoney = value; }
    }
    private long _tianMoney = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"tianMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tianMoney
    {
      get { return _tianMoney; }
      set { _tianMoney = value; }
    }
    private long _diMoney = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"diMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long diMoney
    {
      get { return _diMoney; }
      set { _diMoney = value; }
    }
    private int _peopleNum = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"peopleNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int peopleNum
    {
      get { return _peopleNum; }
      set { _peopleNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TEPlayerListResponse")]
  public partial class TEPlayerListResponse : global::ProtoBuf.IExtensible
  {
    public TEPlayerListResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.RoomPlayerInfoProto> _playerList = new global::System.Collections.Generic.List<com.maple.game.osee.proto.RoomPlayerInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.RoomPlayerInfoProto> playerList
    {
      get { return _playerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TERoomPlayerResponse")]
  public partial class TERoomPlayerResponse : global::ProtoBuf.IExtensible
  {
    public TERoomPlayerResponse() {}
    
    private com.maple.game.osee.proto.RoomPlayerInfoProto _info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.maple.game.osee.proto.RoomPlayerInfoProto info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShakeDiceRequest")]
  public partial class ShakeDiceRequest : global::ProtoBuf.IExtensible
  {
    public ShakeDiceRequest() {}
    
    private int _roomCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShakeDiceResponse")]
  public partial class ShakeDiceResponse : global::ProtoBuf.IExtensible
  {
    public ShakeDiceResponse() {}
    
    private readonly global::System.Collections.Generic.List<int> _dice = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"dice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> dice
    {
      get { return _dice; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomBankerRequest")]
  public partial class RoomBankerRequest : global::ProtoBuf.IExtensible
  {
    public RoomBankerRequest() {}
    
    private int _roomCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomBankerResponse")]
  public partial class RoomBankerResponse : global::ProtoBuf.IExtensible
  {
    public RoomBankerResponse() {}
    
    private bool _isSuccess = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isSuccess", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isSuccess
    {
      get { return _isSuccess; }
      set { _isSuccess = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WaitToBeBankerInfoResponse")]
  public partial class WaitToBeBankerInfoResponse : global::ProtoBuf.IExtensible
  {
    public WaitToBeBankerInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.RoomPlayerInfoProto> _bankerList = new global::System.Collections.Generic.List<com.maple.game.osee.proto.RoomPlayerInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"bankerList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.RoomPlayerInfoProto> bankerList
    {
      get { return _bankerList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BetInFoRequest")]
  public partial class BetInFoRequest : global::ProtoBuf.IExtensible
  {
    public BetInFoRequest() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.BetInfo> _betInfo = new global::System.Collections.Generic.List<com.maple.game.osee.proto.BetInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"betInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.BetInfo> betInfo
    {
      get { return _betInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BetInfoResponse")]
  public partial class BetInfoResponse : global::ProtoBuf.IExtensible
  {
    public BetInfoResponse() {}
    
    private int _res = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int res
    {
      get { return _res; }
      set { _res = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerBetInfoResponse")]
  public partial class PlayerBetInfoResponse : global::ProtoBuf.IExtensible
  {
    public PlayerBetInfoResponse() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.BetInfo> _betInfo = new global::System.Collections.Generic.List<com.maple.game.osee.proto.BetInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"betInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.BetInfo> betInfo
    {
      get { return _betInfo; }
    }
  
    private long _remainMoney = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"remainMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long remainMoney
    {
      get { return _remainMoney; }
      set { _remainMoney = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _allMoney = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(4, Name=@"allMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> allMoney
    {
      get { return _allMoney; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerAllTypeBetMoneyResponse")]
  public partial class PlayerAllTypeBetMoneyResponse : global::ProtoBuf.IExtensible
  {
    public PlayerAllTypeBetMoneyResponse() {}
    
    private long _shunMoney = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"shunMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long shunMoney
    {
      get { return _shunMoney; }
      set { _shunMoney = value; }
    }
    private long _tianMoney = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tianMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tianMoney
    {
      get { return _tianMoney; }
      set { _tianMoney = value; }
    }
    private long _diMoney = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"diMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long diMoney
    {
      get { return _diMoney; }
      set { _diMoney = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReconnectInfoResponse")]
  public partial class ReconnectInfoResponse : global::ProtoBuf.IExtensible
  {
    public ReconnectInfoResponse() {}
    
    private int _roomState = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomState
    {
      get { return _roomState; }
      set { _roomState = value; }
    }
    private int _remainTime = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"remainTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int remainTime
    {
      get { return _remainTime; }
      set { _remainTime = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.CardInfoProto> _cards = new global::System.Collections.Generic.List<com.maple.game.osee.proto.CardInfoProto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.CardInfoProto> cards
    {
      get { return _cards; }
    }
  
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.WinInfoProto> _winInfo = new global::System.Collections.Generic.List<com.maple.game.osee.proto.WinInfoProto>();
    [global::ProtoBuf.ProtoMember(4, Name=@"winInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.WinInfoProto> winInfo
    {
      get { return _winInfo; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _typeShun = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(5, Name=@"typeShun", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> typeShun
    {
      get { return _typeShun; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _typeTian = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(6, Name=@"typeTian", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> typeTian
    {
      get { return _typeTian; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _typeDi = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(7, Name=@"typeDi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> typeDi
    {
      get { return _typeDi; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomBetInfoResponse")]
  public partial class RoomBetInfoResponse : global::ProtoBuf.IExtensible
  {
    public RoomBetInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<long> _typeShun = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"typeShun", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> typeShun
    {
      get { return _typeShun; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _typeTian = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"typeTian", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> typeTian
    {
      get { return _typeTian; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _typeDi = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"typeDi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> typeDi
    {
      get { return _typeDi; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CardInfoResponse")]
  public partial class CardInfoResponse : global::ProtoBuf.IExtensible
  {
    public CardInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.CardInfoProto> _cards = new global::System.Collections.Generic.List<com.maple.game.osee.proto.CardInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.CardInfoProto> cards
    {
      get { return _cards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoundOverResponse")]
  public partial class RoundOverResponse : global::ProtoBuf.IExtensible
  {
    public RoundOverResponse() {}
    
    private long _myScore = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"myScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long myScore
    {
      get { return _myScore; }
      set { _myScore = value; }
    }
    private long _myReturnScore = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"myReturnScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long myReturnScore
    {
      get { return _myReturnScore; }
      set { _myReturnScore = value; }
    }
    private long _bankerScore = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bankerScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bankerScore
    {
      get { return _bankerScore; }
      set { _bankerScore = value; }
    }
    private long _bankerReturnScore = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bankerReturnScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bankerReturnScore
    {
      get { return _bankerReturnScore; }
      set { _bankerReturnScore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WinLoseInfoResponse")]
  public partial class WinLoseInfoResponse : global::ProtoBuf.IExtensible
  {
    public WinLoseInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.WinInfoProto> _winInfo = new global::System.Collections.Generic.List<com.maple.game.osee.proto.WinInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"winInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.WinInfoProto> winInfo
    {
      get { return _winInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WinLoseHistoryInfoResponse")]
  public partial class WinLoseHistoryInfoResponse : global::ProtoBuf.IExtensible
  {
    public WinLoseHistoryInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.WinHistoryInfoProto> _winHistoryInfo = new global::System.Collections.Generic.List<com.maple.game.osee.proto.WinHistoryInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"winHistoryInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.WinHistoryInfoProto> winHistoryInfo
    {
      get { return _winHistoryInfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TwoEightMessageCode")]
    public enum TwoEightMessageCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_TWOEIGHT_JOIN_ROOM_REQUEST", Value=268656641)]
      C_S_TWOEIGHT_JOIN_ROOM_REQUEST = 268656641,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TWOEIGHT_ROOMINFO_RESPONSE", Value=537092099)]
      S_C_TWOEIGHT_ROOMINFO_RESPONSE = 537092099,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_PLAYER_INFO_LIST_RESPONSE", Value=537092100)]
      S_C_TEROOM_PLAYER_INFO_LIST_RESPONSE = 537092100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_PLAYER_INFO_RESPONSE", Value=537092101)]
      S_C_TEROOM_PLAYER_INFO_RESPONSE = 537092101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_SHAKE_DICE_REQUEST", Value=268656646)]
      C_S_SHAKE_DICE_REQUEST = 268656646,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_SHAKE_DICE_REPONSE", Value=537092102)]
      S_C_SHAKE_DICE_REPONSE = 537092102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_TEROOM_BANKER_REQUEST", Value=268656648)]
      C_S_TEROOM_BANKER_REQUEST = 268656648,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_BANKER_RESPONSE", Value=537092104)]
      S_C_TEROOM_BANKER_RESPONSE = 537092104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_TEROOM_QUIT_REQUEST", Value=268656656)]
      C_S_TEROOM_QUIT_REQUEST = 268656656,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_QUIT_RESPONSE", Value=537092112)]
      S_C_TEROOM_QUIT_RESPONSE = 537092112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_TEROMM_BET_REQUEST", Value=268656657)]
      C_S_TEROMM_BET_REQUEST = 268656657,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROMM_BET_RESPONSE", Value=537092113)]
      S_C_TEROMM_BET_RESPONSE = 537092113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_PLAYER_BET_INFO_RESPONSE", Value=537092118)]
      S_C_TEROOM_PLAYER_BET_INFO_RESPONSE = 537092118,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_ROOM_BET_INFO_RESPONSE", Value=537092119)]
      S_C_TEROOM_ROOM_BET_INFO_RESPONSE = 537092119,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_CSRD_RESPONSE", Value=537092115)]
      S_C_TEROOM_CSRD_RESPONSE = 537092115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_ROUND_OVER_RESPONSE", Value=537092116)]
      S_C_TEROOM_ROUND_OVER_RESPONSE = 537092116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_TO_BANKER_RESPONSE", Value=537092117)]
      S_C_TEROOM_TO_BANKER_RESPONSE = 537092117,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_STATE_RESPONSE", Value=537092120)]
      S_C_TEROOM_STATE_RESPONSE = 537092120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_TEROOM_CANCEL_BANKER_REQUEST", Value=268656665)]
      C_S_TEROOM_CANCEL_BANKER_REQUEST = 268656665,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_CANCEL_BANKER_RESPONSE", Value=537092121)]
      S_C_TEROOM_CANCEL_BANKER_RESPONSE = 537092121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_WIN_LOSE_INFO_RESPONSE", Value=537092128)]
      S_C_TEROOM_WIN_LOSE_INFO_RESPONSE = 537092128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_WIN_LOSE_HISTORY_INFO_RESPONSE", Value=537092129)]
      S_C_TEROOM_WIN_LOSE_HISTORY_INFO_RESPONSE = 537092129,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_PLAYER_ALL_TYPE_BET_MONEY_RESPONSE", Value=537092130)]
      S_C_TEROOM_PLAYER_ALL_TYPE_BET_MONEY_RESPONSE = 537092130,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_C_TEROOM_PLAYER_RECONNECT_INFO_RESPONSE", Value=537092131)]
      S_C_TEROOM_PLAYER_RECONNECT_INFO_RESPONSE = 537092131,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_S_TEROOM_PLAYER_RECONNECT_INFO_REQUEST", Value=268656672)]
      C_S_TEROOM_PLAYER_RECONNECT_INFO_REQUEST = 268656672
    }
  
}