//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/OseeFightTenMessage.proto
// Note: requires additional types generated from: proto/OseePublicData.proto
namespace com.maple.game.osee.proto.fightten
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenFieldInfoProto")]
  public partial class TenFieldInfoProto : global::ProtoBuf.IExtensible
  {
    public TenFieldInfoProto() {}
    
    private long _enterMoney = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"enterMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long enterMoney
    {
      get { return _enterMoney; }
      set { _enterMoney = value; }
    }
    private int _type = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenRoomPlayerInfoProto")]
  public partial class TenRoomPlayerInfoProto : global::ProtoBuf.IExtensible
  {
    public TenRoomPlayerInfoProto() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _headIndex = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headIndex
    {
      get { return _headIndex; }
      set { _headIndex = value; }
    }
    private string _headUrl = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"headUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headUrl
    {
      get { return _headUrl; }
      set { _headUrl = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private long _money = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _seat = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private int _readyType = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"readyType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int readyType
    {
      get { return _readyType; }
      set { _readyType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenRoundOverPlayerDataProto")]
  public partial class TenRoundOverPlayerDataProto : global::ProtoBuf.IExtensible
  {
    public TenRoundOverPlayerDataProto() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _seat = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private int _cardType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cardType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int cardType
    {
      get { return _cardType; }
      set { _cardType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private bool _win = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool win
    {
      get { return _win; }
      set { _win = value; }
    }
    private long _winMoney = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"winMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long winMoney
    {
      get { return _winMoney; }
      set { _winMoney = value; }
    }
    private long _myMoney = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"myMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long myMoney
    {
      get { return _myMoney; }
      set { _myMoney = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenTaskInfoProto")]
  public partial class TenTaskInfoProto : global::ProtoBuf.IExtensible
  {
    public TenTaskInfoProto() {}
    
    private long _taskId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long taskId
    {
      get { return _taskId; }
      set { _taskId = value; }
    }
    private string _taskName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"taskName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string taskName
    {
      get { return _taskName; }
      set { _taskName = value; }
    }
    private string _taskInfo = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"taskInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string taskInfo
    {
      get { return _taskInfo; }
      set { _taskInfo = value; }
    }
    private int _targetNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"targetNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int targetNum
    {
      get { return _targetNum; }
      set { _targetNum = value; }
    }
    private int _nowNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"nowNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int nowNum
    {
      get { return _nowNum; }
      set { _nowNum = value; }
    }
    private int _taskState = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"taskState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int taskState
    {
      get { return _taskState; }
      set { _taskState = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto> _rewards = new global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto>();
    [global::ProtoBuf.ProtoMember(7, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto> rewards
    {
      get { return _rewards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenFightBankerProto")]
  public partial class TenFightBankerProto : global::ProtoBuf.IExtensible
  {
    public TenFightBankerProto() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _fightMultiple = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fightMultiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fightMultiple
    {
      get { return _fightMultiple; }
      set { _fightMultiple = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenBetMoneyProto")]
  public partial class TenBetMoneyProto : global::ProtoBuf.IExtensible
  {
    public TenBetMoneyProto() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private long _betMoney = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"betMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long betMoney
    {
      get { return _betMoney; }
      set { _betMoney = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenGetFieldListRequest")]
  public partial class TenGetFieldListRequest : global::ProtoBuf.IExtensible
  {
    public TenGetFieldListRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenGetFieldListResponse")]
  public partial class TenGetFieldListResponse : global::ProtoBuf.IExtensible
  {
    public TenGetFieldListResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFieldInfoProto> _fieldInfos = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFieldInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"fieldInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFieldInfoProto> fieldInfos
    {
      get { return _fieldInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenJoinRoomRequest")]
  public partial class TenJoinRoomRequest : global::ProtoBuf.IExtensible
  {
    public TenJoinRoomRequest() {}
    
    private int _fieldType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fieldType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fieldType
    {
      get { return _fieldType; }
      set { _fieldType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenRoomInfoResponse")]
  public partial class TenRoomInfoResponse : global::ProtoBuf.IExtensible
  {
    public TenRoomInfoResponse() {}
    
    private int _roomCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private int _fieldType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fieldType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fieldType
    {
      get { return _fieldType; }
      set { _fieldType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenRoomPlayerInfoResponse")]
  public partial class TenRoomPlayerInfoResponse : global::ProtoBuf.IExtensible
  {
    public TenRoomPlayerInfoResponse() {}
    
    private com.maple.game.osee.proto.fightten.TenRoomPlayerInfoProto _playerInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.maple.game.osee.proto.fightten.TenRoomPlayerInfoProto playerInfo
    {
      get { return _playerInfo; }
      set { _playerInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenRoomPlayerInfoListResponse")]
  public partial class TenRoomPlayerInfoListResponse : global::ProtoBuf.IExtensible
  {
    public TenRoomPlayerInfoListResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoomPlayerInfoProto> _playerInfos = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoomPlayerInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoomPlayerInfoProto> playerInfos
    {
      get { return _playerInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChangeRoomStateResponse")]
  public partial class TenChangeRoomStateResponse : global::ProtoBuf.IExtensible
  {
    public TenChangeRoomStateResponse() {}
    
    private int _roomState = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomState
    {
      get { return _roomState; }
      set { _roomState = value; }
    }
    private int _stateRestTime = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stateRestTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stateRestTime
    {
      get { return _stateRestTime; }
      set { _stateRestTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenReadyRoomRequest")]
  public partial class TenReadyRoomRequest : global::ProtoBuf.IExtensible
  {
    public TenReadyRoomRequest() {}
    
    private int _readyType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"readyType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int readyType
    {
      get { return _readyType; }
      set { _readyType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenReadyRoomResponse")]
  public partial class TenReadyRoomResponse : global::ProtoBuf.IExtensible
  {
    public TenReadyRoomResponse() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _readyType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"readyType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int readyType
    {
      get { return _readyType; }
      set { _readyType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenDispatchCardResponse")]
  public partial class TenDispatchCardResponse : global::ProtoBuf.IExtensible
  {
    public TenDispatchCardResponse() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private int _seat = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenFightBankerRequest")]
  public partial class TenFightBankerRequest : global::ProtoBuf.IExtensible
  {
    public TenFightBankerRequest() {}
    
    private int _fightMultiple = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fightMultiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fightMultiple
    {
      get { return _fightMultiple; }
      set { _fightMultiple = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenFightBankerResponse")]
  public partial class TenFightBankerResponse : global::ProtoBuf.IExtensible
  {
    public TenFightBankerResponse() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _fightMultiple = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fightMultiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fightMultiple
    {
      get { return _fightMultiple; }
      set { _fightMultiple = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenSelectBankerResponse")]
  public partial class TenSelectBankerResponse : global::ProtoBuf.IExtensible
  {
    public TenSelectBankerResponse() {}
    
    private long _bankerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bankerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bankerId
    {
      get { return _bankerId; }
      set { _bankerId = value; }
    }
    private int _bankerFightMultiple = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bankerFightMultiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bankerFightMultiple
    {
      get { return _bankerFightMultiple; }
      set { _bankerFightMultiple = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _randomPlayerIdList = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"randomPlayerIdList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> randomPlayerIdList
    {
      get { return _randomPlayerIdList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenBetMoneyListResponse")]
  public partial class TenBetMoneyListResponse : global::ProtoBuf.IExtensible
  {
    public TenBetMoneyListResponse() {}
    
    private readonly global::System.Collections.Generic.List<long> _betMoneyList = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"betMoneyList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> betMoneyList
    {
      get { return _betMoneyList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenBetMoneyRequest")]
  public partial class TenBetMoneyRequest : global::ProtoBuf.IExtensible
  {
    public TenBetMoneyRequest() {}
    
    private int _betMoneyIndex = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"betMoneyIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int betMoneyIndex
    {
      get { return _betMoneyIndex; }
      set { _betMoneyIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenBetMoneyResponse")]
  public partial class TenBetMoneyResponse : global::ProtoBuf.IExtensible
  {
    public TenBetMoneyResponse() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private long _betMoney = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"betMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long betMoney
    {
      get { return _betMoney; }
      set { _betMoney = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenSendLastCardResponse")]
  public partial class TenSendLastCardResponse : global::ProtoBuf.IExtensible
  {
    public TenSendLastCardResponse() {}
    
    private int _lastCard = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"lastCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lastCard
    {
      get { return _lastCard; }
      set { _lastCard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenSeeCardRequest")]
  public partial class TenSeeCardRequest : global::ProtoBuf.IExtensible
  {
    public TenSeeCardRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenSeeCardResponse")]
  public partial class TenSeeCardResponse : global::ProtoBuf.IExtensible
  {
    public TenSeeCardResponse() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenRubCardRequest")]
  public partial class TenRubCardRequest : global::ProtoBuf.IExtensible
  {
    public TenRubCardRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenRubCardResponse")]
  public partial class TenRubCardResponse : global::ProtoBuf.IExtensible
  {
    public TenRubCardResponse() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenRoundOverResponse")]
  public partial class TenRoundOverResponse : global::ProtoBuf.IExtensible
  {
    public TenRoundOverResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoundOverPlayerDataProto> _playerData = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoundOverPlayerDataProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"playerData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoundOverPlayerDataProto> playerData
    {
      get { return _playerData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenLeaveRoomRequest")]
  public partial class TenLeaveRoomRequest : global::ProtoBuf.IExtensible
  {
    public TenLeaveRoomRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenLeaveRoomResponse")]
  public partial class TenLeaveRoomResponse : global::ProtoBuf.IExtensible
  {
    public TenLeaveRoomResponse() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChangeRoomRequest")]
  public partial class TenChangeRoomRequest : global::ProtoBuf.IExtensible
  {
    public TenChangeRoomRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenTaskListRequest")]
  public partial class TenTaskListRequest : global::ProtoBuf.IExtensible
  {
    public TenTaskListRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenTaskListResponse")]
  public partial class TenTaskListResponse : global::ProtoBuf.IExtensible
  {
    public TenTaskListResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenTaskInfoProto> _taskInfos = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenTaskInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"taskInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenTaskInfoProto> taskInfos
    {
      get { return _taskInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenGetTaskRewardRequest")]
  public partial class TenGetTaskRewardRequest : global::ProtoBuf.IExtensible
  {
    public TenGetTaskRewardRequest() {}
    
    private long _taskId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long taskId
    {
      get { return _taskId; }
      set { _taskId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenReconnectResponse")]
  public partial class TenReconnectResponse : global::ProtoBuf.IExtensible
  {
    public TenReconnectResponse() {}
    
    private int _roomCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private long _maxBetMoney = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"maxBetMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long maxBetMoney
    {
      get { return _maxBetMoney; }
      set { _maxBetMoney = value; }
    }
    private int _roomState = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomState
    {
      get { return _roomState; }
      set { _roomState = value; }
    }
    private int _stateRestTime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stateRestTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stateRestTime
    {
      get { return _stateRestTime; }
      set { _stateRestTime = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _readyPlayers = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(5, Name=@"readyPlayers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> readyPlayers
    {
      get { return _readyPlayers; }
    }
  
    private int _seat = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFightBankerProto> _fightedBankerProto = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFightBankerProto>();
    [global::ProtoBuf.ProtoMember(8, Name=@"fightedBankerProto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFightBankerProto> fightedBankerProto
    {
      get { return _fightedBankerProto; }
    }
  
    private long _bankerId = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"bankerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bankerId
    {
      get { return _bankerId; }
      set { _bankerId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFightBankerProto> _fightBankerProto = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFightBankerProto>();
    [global::ProtoBuf.ProtoMember(10, Name=@"fightBankerProto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFightBankerProto> fightBankerProto
    {
      get { return _fightBankerProto; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _aniPlayerId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(11, Name=@"aniPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> aniPlayerId
    {
      get { return _aniPlayerId; }
    }
  
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenBetMoneyProto> _betMoneyProto = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenBetMoneyProto>();
    [global::ProtoBuf.ProtoMember(12, Name=@"betMoneyProto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenBetMoneyProto> betMoneyProto
    {
      get { return _betMoneyProto; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _betMoneyList = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(13, Name=@"betMoneyList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> betMoneyList
    {
      get { return _betMoneyList; }
    }
  
    private int _lastCard = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"lastCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lastCard
    {
      get { return _lastCard; }
      set { _lastCard = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _seeOrRubCardPlayer = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(15, Name=@"seeOrRubCardPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> seeOrRubCardPlayer
    {
      get { return _seeOrRubCardPlayer; }
    }
  
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoundOverPlayerDataProto> _roundOverProto = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoundOverPlayerDataProto>();
    [global::ProtoBuf.ProtoMember(16, Name=@"roundOverProto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoundOverPlayerDataProto> roundOverProto
    {
      get { return _roundOverProto; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenGiveGiftRequest")]
  public partial class TenGiveGiftRequest : global::ProtoBuf.IExtensible
  {
    public TenGiveGiftRequest() {}
    
    private long _toPlayerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"toPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long toPlayerId
    {
      get { return _toPlayerId; }
      set { _toPlayerId = value; }
    }
    private int _giftType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"giftType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int giftType
    {
      get { return _giftType; }
      set { _giftType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenGiveGiftResponse")]
  public partial class TenGiveGiftResponse : global::ProtoBuf.IExtensible
  {
    public TenGiveGiftResponse() {}
    
    private long _toPlayerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"toPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long toPlayerId
    {
      get { return _toPlayerId; }
      set { _toPlayerId = value; }
    }
    private long _fromPlayerId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fromPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long fromPlayerId
    {
      get { return _fromPlayerId; }
      set { _fromPlayerId = value; }
    }
    private int _giftType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"giftType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int giftType
    {
      get { return _giftType; }
      set { _giftType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FightTenBonusResponse")]
  public partial class FightTenBonusResponse : global::ProtoBuf.IExtensible
  {
    public FightTenBonusResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto> _items = new global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto> items
    {
      get { return _items; }
    }
  
    private long _type = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}