//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/OseeBaiRenTenMessage.proto
namespace com.maple.game.osee.proto.bairen
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenRoomPlayerInfoProto")]
  public partial class BaiRenRoomPlayerInfoProto : global::ProtoBuf.IExtensible
  {
    public BaiRenRoomPlayerInfoProto() {}
    
    private string _nickname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private long _money = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private string _head = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"head", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string head
    {
      get { return _head; }
      set { _head = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenRoomInfoProto")]
  public partial class BaiRenRoomInfoProto : global::ProtoBuf.IExtensible
  {
    public BaiRenRoomInfoProto() {}
    
    private int _roomCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private long _moneyLimit = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"moneyLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long moneyLimit
    {
      get { return _moneyLimit; }
      set { _moneyLimit = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _stateTime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stateTime
    {
      get { return _stateTime; }
      set { _stateTime = value; }
    }
    private long _bankerId = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bankerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bankerId
    {
      get { return _bankerId; }
      set { _bankerId = value; }
    }
    private string _zhuangName = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"zhuangName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string zhuangName
    {
      get { return _zhuangName; }
      set { _zhuangName = value; }
    }
    private long _zhuangMoney = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"zhuangMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long zhuangMoney
    {
      get { return _zhuangMoney; }
      set { _zhuangMoney = value; }
    }
    private long _allBet = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"allBet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long allBet
    {
      get { return _allBet; }
      set { _allBet = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomBetInfoProto> _baiRenBet = new global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomBetInfoProto>();
    [global::ProtoBuf.ProtoMember(9, Name=@"baiRenBet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomBetInfoProto> baiRenBet
    {
      get { return _baiRenBet; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _itemTransId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"itemTransId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> itemTransId
    {
      get { return _itemTransId; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _itemTransIdList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"itemTransIdList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> itemTransIdList
    {
      get { return _itemTransIdList; }
    }
  
    private int _bankersLength = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"bankersLength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bankersLength
    {
      get { return _bankersLength; }
      set { _bankersLength = value; }
    }
    private int _playerNum = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"playerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerNum
    {
      get { return _playerNum; }
      set { _playerNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenRoomBetInfoProto")]
  public partial class BaiRenRoomBetInfoProto : global::ProtoBuf.IExtensible
  {
    public BaiRenRoomBetInfoProto() {}
    
    private int _itemId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private long _money = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _mut = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"mut", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mut
    {
      get { return _mut; }
      set { _mut = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _carList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"carList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> carList
    {
      get { return _carList; }
    }
  
    private int _carTpye = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"carTpye", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int carTpye
    {
      get { return _carTpye; }
      set { _carTpye = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRoomRequest")]
  public partial class JoinRoomRequest : global::ProtoBuf.IExtensible
  {
    public JoinRoomRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenJoinRoomResponse")]
  public partial class BaiRenJoinRoomResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenJoinRoomResponse() {}
    
    private com.maple.game.osee.proto.bairen.BaiRenRoomInfoProto _roomInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.maple.game.osee.proto.bairen.BaiRenRoomInfoProto roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenExitRoomRequest")]
  public partial class BaiRenExitRoomRequest : global::ProtoBuf.IExtensible
  {
    public BaiRenExitRoomRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenExitRoomResponse")]
  public partial class BaiRenExitRoomResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenExitRoomResponse() {}
    
    private int _code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenBetRequest")]
  public partial class BaiRenBetRequest : global::ProtoBuf.IExtensible
  {
    public BaiRenBetRequest() {}
    
    private int _itemId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private int _itemMoney = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemMoney
    {
      get { return _itemMoney; }
      set { _itemMoney = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenBetResponse")]
  public partial class BaiRenBetResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenBetResponse() {}
    
    private int _code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenBetInfoResponse")]
  public partial class BaiRenBetInfoResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenBetInfoResponse() {}
    
    private long _allBet = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"allBet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long allBet
    {
      get { return _allBet; }
      set { _allBet = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomBetInfoProto> _baiRenBet = new global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomBetInfoProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"baiRenBet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomBetInfoProto> baiRenBet
    {
      get { return _baiRenBet; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenLastBetRequest")]
  public partial class BaiRenLastBetRequest : global::ProtoBuf.IExtensible
  {
    public BaiRenLastBetRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenLastBetResponse")]
  public partial class BaiRenLastBetResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenLastBetResponse() {}
    
    private int _code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenStatementInfoRequest")]
  public partial class BaiRenStatementInfoRequest : global::ProtoBuf.IExtensible
  {
    public BaiRenStatementInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenStatementInfoResponse")]
  public partial class BaiRenStatementInfoResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenStatementInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<int> _itemTransId = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"itemTransId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> itemTransId
    {
      get { return _itemTransId; }
    }
  
    private long _bankerId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bankerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bankerId
    {
      get { return _bankerId; }
      set { _bankerId = value; }
    }
    private long _bankerProfit = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bankerProfit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bankerProfit
    {
      get { return _bankerProfit; }
      set { _bankerProfit = value; }
    }
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private long _playerProfit = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"playerProfit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerProfit
    {
      get { return _playerProfit; }
      set { _playerProfit = value; }
    }
    private long _zhuangMoney = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"zhuangMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long zhuangMoney
    {
      get { return _zhuangMoney; }
      set { _zhuangMoney = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomBetInfoProto> _baiRenBet = new global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomBetInfoProto>();
    [global::ProtoBuf.ProtoMember(7, Name=@"baiRenBet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomBetInfoProto> baiRenBet
    {
      get { return _baiRenBet; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _itemTransIdList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"itemTransIdList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> itemTransIdList
    {
      get { return _itemTransIdList; }
    }
  
    private int _profitStatus = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"profitStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profitStatus
    {
      get { return _profitStatus; }
      set { _profitStatus = value; }
    }
    private int _itemId = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenApplyForBankerRequest")]
  public partial class BaiRenApplyForBankerRequest : global::ProtoBuf.IExtensible
  {
    public BaiRenApplyForBankerRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenApplyForBankerResponse")]
  public partial class BaiRenApplyForBankerResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenApplyForBankerResponse() {}
    
    private int _code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private long _bankerId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bankerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bankerId
    {
      get { return _bankerId; }
      set { _bankerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenGetRoomStatusInfoRequest")]
  public partial class BaiRenGetRoomStatusInfoRequest : global::ProtoBuf.IExtensible
  {
    public BaiRenGetRoomStatusInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenGetRoomStatusInfoResponse")]
  public partial class BaiRenGetRoomStatusInfoResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenGetRoomStatusInfoResponse() {}
    
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _stateTime = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stateTime
    {
      get { return _stateTime; }
      set { _stateTime = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _itemTransIdList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"itemTransIdList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> itemTransIdList
    {
      get { return _itemTransIdList; }
    }
  
    private string _bankerName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bankerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string bankerName
    {
      get { return _bankerName; }
      set { _bankerName = value; }
    }
    private int _playerNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"playerNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerNum
    {
      get { return _playerNum; }
      set { _playerNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenGetRoomPlayersInfoRequest")]
  public partial class BaiRenGetRoomPlayersInfoRequest : global::ProtoBuf.IExtensible
  {
    public BaiRenGetRoomPlayersInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenGetRoomPlayersInfoResponse")]
  public partial class BaiRenGetRoomPlayersInfoResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenGetRoomPlayersInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomPlayerInfoProto> _players = new global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomPlayerInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomPlayerInfoProto> players
    {
      get { return _players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenGetRoomBankersInfoRequest")]
  public partial class BaiRenGetRoomBankersInfoRequest : global::ProtoBuf.IExtensible
  {
    public BaiRenGetRoomBankersInfoRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenGetRoomBankersInfoResponse")]
  public partial class BaiRenGetRoomBankersInfoResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenGetRoomBankersInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomPlayerInfoProto> _players = new global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomPlayerInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomPlayerInfoProto> players
    {
      get { return _players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenOtherBetInfoResponse")]
  public partial class BaiRenOtherBetInfoResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenOtherBetInfoResponse() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _itemId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private long _money = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenDiscontinueBankerRequest")]
  public partial class BaiRenDiscontinueBankerRequest : global::ProtoBuf.IExtensible
  {
    public BaiRenDiscontinueBankerRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenDiscontinueBankerResponse")]
  public partial class BaiRenDiscontinueBankerResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenDiscontinueBankerResponse() {}
    
    private int _code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BaiRenUserBetInfoResponse")]
  public partial class BaiRenUserBetInfoResponse : global::ProtoBuf.IExtensible
  {
    public BaiRenUserBetInfoResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomBetInfoProto> _baiRenBet = new global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomBetInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"baiRenBet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.bairen.BaiRenRoomBetInfoProto> baiRenBet
    {
      get { return _baiRenBet; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}