//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/OseePublicData.proto
namespace com.maple.game.osee.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BackgroundSyncRequest")]
  public partial class BackgroundSyncRequest : global::ProtoBuf.IExtensible
  {
    public BackgroundSyncRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BackgroundSyncResponse")]
  public partial class BackgroundSyncResponse : global::ProtoBuf.IExtensible
  {
    public BackgroundSyncResponse() {}
    
    private long _fishId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }
    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemDataProto")]
  public partial class ItemDataProto : global::ProtoBuf.IExtensible
  {
    public ItemDataProto() {}
    
    private int _itemId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private long _itemNum = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemNum
    {
      get { return _itemNum; }
      set { _itemNum = value; }
    }
    private long _originalNumber = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"originalNumber", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long originalNumber
    {
      get { return _originalNumber; }
      set { _originalNumber = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FruitLaBaWinLineDataProto")]
  public partial class FruitLaBaWinLineDataProto : global::ProtoBuf.IExtensible
  {
    public FruitLaBaWinLineDataProto() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.FruitLaBaSpotProto> _winLinePoints = new global::System.Collections.Generic.List<com.maple.game.osee.proto.FruitLaBaSpotProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"winLinePoints", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.FruitLaBaSpotProto> winLinePoints
    {
      get { return _winLinePoints; }
    }
  
    private int _winNum = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"winNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winNum
    {
      get { return _winNum; }
      set { _winNum = value; }
    }
    private int _winType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"winType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int winType
    {
      get { return _winType; }
      set { _winType = value; }
    }
    private long _lineGold = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lineGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lineGold
    {
      get { return _lineGold; }
      set { _lineGold = value; }
    }
    private int _lineMultiple = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"lineMultiple", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lineMultiple
    {
      get { return _lineMultiple; }
      set { _lineMultiple = value; }
    }
    private int _lineName = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"lineName", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lineName
    {
      get { return _lineName; }
      set { _lineName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FruitLaBaWinSpecialRewardProto")]
  public partial class FruitLaBaWinSpecialRewardProto : global::ProtoBuf.IExtensible
  {
    public FruitLaBaWinSpecialRewardProto() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.FruitLaBaSpotProto> _specialSpots = new global::System.Collections.Generic.List<com.maple.game.osee.proto.FruitLaBaSpotProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"specialSpots", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.FruitLaBaSpotProto> specialSpots
    {
      get { return _specialSpots; }
    }
  
    private int _specialType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"specialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int specialType
    {
      get { return _specialType; }
      set { _specialType = value; }
    }
    private long _winNum = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"winNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long winNum
    {
      get { return _winNum; }
      set { _winNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FruitLaBaSpotProto")]
  public partial class FruitLaBaSpotProto : global::ProtoBuf.IExtensible
  {
    public FruitLaBaSpotProto() {}
    
    private int _rankSpot = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rankSpot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rankSpot
    {
      get { return _rankSpot; }
      set { _rankSpot = value; }
    }
    private int _verticalSpot = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"verticalSpot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int verticalSpot
    {
      get { return _verticalSpot; }
      set { _verticalSpot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FruitLaBaRewardInfoProto")]
  public partial class FruitLaBaRewardInfoProto : global::ProtoBuf.IExtensible
  {
    public FruitLaBaRewardInfoProto() {}
    
    private int _achieveNum = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"achieveNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int achieveNum
    {
      get { return _achieveNum; }
      set { _achieveNum = value; }
    }
    private int _rewardGold = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rewardGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rewardGold
    {
      get { return _rewardGold; }
      set { _rewardGold = value; }
    }
    private int _rewardLottery = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rewardLottery", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int rewardLottery
    {
      get { return _rewardLottery; }
      set { _rewardLottery = value; }
    }
    private bool _weatherReceive = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"weatherReceive", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool weatherReceive
    {
      get { return _weatherReceive; }
      set { _weatherReceive = value; }
    }
    private long _rewardId = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rewardId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long rewardId
    {
      get { return _rewardId; }
      set { _rewardId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageInfoProto")]
  public partial class MessageInfoProto : global::ProtoBuf.IExtensible
  {
    public MessageInfoProto() {}
    
    private long _id = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private bool _read = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"read", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool read
    {
      get { return _read; }
      set { _read = value; }
    }
    private bool _receive = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"receive", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool receive
    {
      get { return _receive; }
      set { _receive = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto> _items = new global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto>();
    [global::ProtoBuf.ProtoMember(7, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FunctionStateProto")]
  public partial class FunctionStateProto : global::ProtoBuf.IExtensible
  {
    public FunctionStateProto() {}
    
    private int _funcId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"funcId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int funcId
    {
      get { return _funcId; }
      set { _funcId = value; }
    }
    private bool _state = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskInfoProto")]
  public partial class TaskInfoProto : global::ProtoBuf.IExtensible
  {
    public TaskInfoProto() {}
    
    private long _taskId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"taskId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long taskId
    {
      get { return _taskId; }
      set { _taskId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _info = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private int _active = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"active", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int active
    {
      get { return _active; }
      set { _active = value; }
    }
    private int _progress = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private int _target = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int target
    {
      get { return _target; }
      set { _target = value; }
    }
    private bool _receive = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"receive", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool receive
    {
      get { return _receive; }
      set { _receive = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto> _rewards = new global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto>();
    [global::ProtoBuf.ProtoMember(8, Name=@"rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto> rewards
    {
      get { return _rewards; }
    }
  
    private int _goalType = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"goalType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int goalType
    {
      get { return _goalType; }
      set { _goalType = value; }
    }
    private string _goalId = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"goalId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string goalId
    {
      get { return _goalId; }
      set { _goalId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetPayWayRequest")]
  public partial class GetPayWayRequest : global::ProtoBuf.IExtensible
  {
    public GetPayWayRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetPayWayResponse")]
  public partial class GetPayWayResponse : global::ProtoBuf.IExtensible
  {
    public GetPayWayResponse() {}
    
    private int _payWay = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"payWay", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int payWay
    {
      get { return _payWay; }
      set { _payWay = value; }
    }
    private bool _state = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseEleRequest")]
  public partial class UseEleRequest : global::ProtoBuf.IExtensible
  {
    public UseEleRequest() {}
    
    private long _fishId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseEleResponse")]
  public partial class UseEleResponse : global::ProtoBuf.IExtensible
  {
    public UseEleResponse() {}
    
    private long _fishId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReceiveItemsResponse")]
  public partial class ReceiveItemsResponse : global::ProtoBuf.IExtensible
  {
    public ReceiveItemsResponse() {}
    
    private long _fromPlayerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fromPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long fromPlayerId
    {
      get { return _fromPlayerId; }
      set { _fromPlayerId = value; }
    }
    private long _toPlayerId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"toPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long toPlayerId
    {
      get { return _toPlayerId; }
      set { _toPlayerId = value; }
    }
    private long _time = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long time
    {
      get { return _time; }
      set { _time = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto> _items = new global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto>();
    [global::ProtoBuf.ProtoMember(4, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerStatusRequest")]
  public partial class PlayerStatusRequest : global::ProtoBuf.IExtensible
  {
    public PlayerStatusRequest() {}
    
    private long _index = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerStatusResponse")]
  public partial class PlayerStatusResponse : global::ProtoBuf.IExtensible
  {
    public PlayerStatusResponse() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private long _datetime = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"datetime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long datetime
    {
      get { return _datetime; }
      set { _datetime = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRoomStatusRequest")]
  public partial class PlayerRoomStatusRequest : global::ProtoBuf.IExtensible
  {
    public PlayerRoomStatusRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRoomStatusResponse")]
  public partial class PlayerRoomStatusResponse : global::ProtoBuf.IExtensible
  {
    public PlayerRoomStatusResponse() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private long _datetime = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"datetime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long datetime
    {
      get { return _datetime; }
      set { _datetime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerPropResponse")]
  public partial class PlayerPropResponse : global::ProtoBuf.IExtensible
  {
    public PlayerPropResponse() {}
    
    private long _bronzeTorpedo = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bronzeTorpedo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bronzeTorpedo
    {
      get { return _bronzeTorpedo; }
      set { _bronzeTorpedo = value; }
    }
    private long _silverTorpedo = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"silverTorpedo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long silverTorpedo
    {
      get { return _silverTorpedo; }
      set { _silverTorpedo = value; }
    }
    private long _goldTorpedo = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"goldTorpedo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long goldTorpedo
    {
      get { return _goldTorpedo; }
      set { _goldTorpedo = value; }
    }
    private long _skillLock = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"skillLock", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long skillLock
    {
      get { return _skillLock; }
      set { _skillLock = value; }
    }
    private long _skillFrozen = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"skillFrozen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long skillFrozen
    {
      get { return _skillFrozen; }
      set { _skillFrozen = value; }
    }
    private long _skillFast = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"skillFast", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long skillFast
    {
      get { return _skillFast; }
      set { _skillFast = value; }
    }
    private long _skillCrit = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"skillCrit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long skillCrit
    {
      get { return _skillCrit; }
      set { _skillCrit = value; }
    }
    private long _monthCardOverDate = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"monthCardOverDate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long monthCardOverDate
    {
      get { return _monthCardOverDate; }
      set { _monthCardOverDate = value; }
    }
    private long _bossBugle = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"bossBugle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bossBugle
    {
      get { return _bossBugle; }
      set { _bossBugle = value; }
    }
    private long _qszs = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"qszs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long qszs
    {
      get { return _qszs; }
      set { _qszs = value; }
    }
    private long _blnh = default(long);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"blnh", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long blnh
    {
      get { return _blnh; }
      set { _blnh = value; }
    }
    private long _lhtz = default(long);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"lhtz", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lhtz
    {
      get { return _lhtz; }
      set { _lhtz = value; }
    }
    private long _swhp = default(long);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"swhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long swhp
    {
      get { return _swhp; }
      set { _swhp = value; }
    }
    private long _fenShen = default(long);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"fenShen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long fenShen
    {
      get { return _fenShen; }
      set { _fenShen = value; }
    }
    private long _goldTorpedoBang = default(long);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"goldTorpedoBang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long goldTorpedoBang
    {
      get { return _goldTorpedoBang; }
      set { _goldTorpedoBang = value; }
    }
    private long _dianchipao = default(long);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"dianchipao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long dianchipao
    {
      get { return _dianchipao; }
      set { _dianchipao = value; }
    }
    private long _rareTorpedo = default(long);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"rareTorpedo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long rareTorpedo
    {
      get { return _rareTorpedo; }
      set { _rareTorpedo = value; }
    }
    private long _rareTorpedoBang = default(long);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"rareTorpedoBang", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long rareTorpedoBang
    {
      get { return _rareTorpedoBang; }
      set { _rareTorpedoBang = value; }
    }
    private long _yuGu = default(long);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"yuGu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long yuGu
    {
      get { return _yuGu; }
      set { _yuGu = value; }
    }
    private long _haiYaoShi = default(long);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"haiYaoShi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long haiYaoShi
    {
      get { return _haiYaoShi; }
      set { _haiYaoShi = value; }
    }
    private long _wangHunShi = default(long);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"wangHunShi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long wangHunShi
    {
      get { return _wangHunShi; }
      set { _wangHunShi = value; }
    }
    private long _haiHunShi = default(long);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"haiHunShi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long haiHunShi
    {
      get { return _haiHunShi; }
      set { _haiHunShi = value; }
    }
    private long _zhenZhuShi = default(long);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"zhenZhuShi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long zhenZhuShi
    {
      get { return _zhenZhuShi; }
      set { _zhenZhuShi = value; }
    }
    private long _haiShouShi = default(long);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"haiShouShi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long haiShouShi
    {
      get { return _haiShouShi; }
      set { _haiShouShi = value; }
    }
    private long _haiMoShi = default(long);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"haiMoShi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long haiMoShi
    {
      get { return _haiMoShi; }
      set { _haiMoShi = value; }
    }
    private long _zhaoHunShi = default(long);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"zhaoHunShi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long zhaoHunShi
    {
      get { return _zhaoHunShi; }
      set { _zhaoHunShi = value; }
    }
    private long _dianCiShi = default(long);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"dianCiShi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long dianCiShi
    {
      get { return _dianCiShi; }
      set { _dianCiShi = value; }
    }
    private long _heiDongShi = default(long);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"heiDongShi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long heiDongShi
    {
      get { return _heiDongShi; }
      set { _heiDongShi = value; }
    }
    private long _lingZhuShi = default(long);
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"lingZhuShi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lingZhuShi
    {
      get { return _lingZhuShi; }
      set { _lingZhuShi = value; }
    }
    private long _longGu = default(long);
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"longGu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long longGu
    {
      get { return _longGu; }
      set { _longGu = value; }
    }
    private long _longZhu = default(long);
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"longZhu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long longZhu
    {
      get { return _longZhu; }
      set { _longZhu = value; }
    }
    private long _longYuan = default(long);
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"longYuan", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long longYuan
    {
      get { return _longYuan; }
      set { _longYuan = value; }
    }
    private long _longJi = default(long);
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"longJi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long longJi
    {
      get { return _longJi; }
      set { _longJi = value; }
    }
    private long _heiDongPao = default(long);
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"heiDongPao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long heiDongPao
    {
      get { return _heiDongPao; }
      set { _heiDongPao = value; }
    }
    private long _yuLeiPao = default(long);
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"yuLeiPao", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long yuLeiPao
    {
      get { return _yuLeiPao; }
      set { _yuLeiPao = value; }
    }
    private long _sendCard = default(long);
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"sendCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sendCard
    {
      get { return _sendCard; }
      set { _sendCard = value; }
    }
    private long _blackBullet = default(long);
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"blackBullet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long blackBullet
    {
      get { return _blackBullet; }
      set { _blackBullet = value; }
    }
    private long _bronzeBullet = default(long);
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"bronzeBullet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bronzeBullet
    {
      get { return _bronzeBullet; }
      set { _bronzeBullet = value; }
    }
    private long _silverBullet = default(long);
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"silverBullet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long silverBullet
    {
      get { return _silverBullet; }
      set { _silverBullet = value; }
    }
    private long _goldBullet = default(long);
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"goldBullet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long goldBullet
    {
      get { return _goldBullet; }
      set { _goldBullet = value; }
    }
    private long _lbs = default(long);
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"lbs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lbs
    {
      get { return _lbs; }
      set { _lbs = value; }
    }
    private long _tjzx = default(long);
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"tjzx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tjzx
    {
      get { return _tjzx; }
      set { _tjzx = value; }
    }
    private long _hjhp = default(long);
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"hjhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long hjhp
    {
      get { return _hjhp; }
      set { _hjhp = value; }
    }
    private long _gjzy = default(long);
    [global::ProtoBuf.ProtoMember(44, IsRequired = false, Name=@"gjzy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long gjzy
    {
      get { return _gjzy; }
      set { _gjzy = value; }
    }
    private long _hjzp = default(long);
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"hjzp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long hjzp
    {
      get { return _hjzp; }
      set { _hjzp = value; }
    }
    private long _zlhp = default(long);
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"zlhp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long zlhp
    {
      get { return _zlhp; }
      set { _zlhp = value; }
    }
    private long _skillBit = default(long);
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"skillBit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long skillBit
    {
      get { return _skillBit; }
      set { _skillBit = value; }
    }
    private string _useBatteryView = "";
    [global::ProtoBuf.ProtoMember(48, IsRequired = false, Name=@"useBatteryView", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string useBatteryView
    {
      get { return _useBatteryView; }
      set { _useBatteryView = value; }
    }
    private string _data = "";
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerPropOneResponse")]
  public partial class PlayerPropOneResponse : global::ProtoBuf.IExtensible
  {
    public PlayerPropOneResponse() {}
    
    private long _itemId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private long _itemNum = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemNum
    {
      get { return _itemNum; }
      set { _itemNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseBlackRequest")]
  public partial class UseBlackRequest : global::ProtoBuf.IExtensible
  {
    public UseBlackRequest() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseBlackResponse")]
  public partial class UseBlackResponse : global::ProtoBuf.IExtensible
  {
    public UseBlackResponse() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseTroRequest")]
  public partial class UseTroRequest : global::ProtoBuf.IExtensible
  {
    public UseTroRequest() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseTroResponse")]
  public partial class UseTroResponse : global::ProtoBuf.IExtensible
  {
    public UseTroResponse() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseBitRequest")]
  public partial class UseBitRequest : global::ProtoBuf.IExtensible
  {
    public UseBitRequest() {}
    
    private float _angle = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UseBitResponse")]
  public partial class UseBitResponse : global::ProtoBuf.IExtensible
  {
    public UseBitResponse() {}
    
    private float _angle = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChallengeUseEleRequest")]
  public partial class ChallengeUseEleRequest : global::ProtoBuf.IExtensible
  {
    public ChallengeUseEleRequest() {}
    
    private long _fishId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChallengeUseEleResponse")]
  public partial class ChallengeUseEleResponse : global::ProtoBuf.IExtensible
  {
    public ChallengeUseEleResponse() {}
    
    private long _fishId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChallengeUseBlackRequest")]
  public partial class ChallengeUseBlackRequest : global::ProtoBuf.IExtensible
  {
    public ChallengeUseBlackRequest() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChallengeUseBlackResponse")]
  public partial class ChallengeUseBlackResponse : global::ProtoBuf.IExtensible
  {
    public ChallengeUseBlackResponse() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChallengeUseTroRequest")]
  public partial class ChallengeUseTroRequest : global::ProtoBuf.IExtensible
  {
    public ChallengeUseTroRequest() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChallengeUseTroResponse")]
  public partial class ChallengeUseTroResponse : global::ProtoBuf.IExtensible
  {
    public ChallengeUseTroResponse() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChallengeUseBitRequest")]
  public partial class ChallengeUseBitRequest : global::ProtoBuf.IExtensible
  {
    public ChallengeUseBitRequest() {}
    
    private float _angle = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChallengeUseBitResponse")]
  public partial class ChallengeUseBitResponse : global::ProtoBuf.IExtensible
  {
    public ChallengeUseBitResponse() {}
    
    private float _angle = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GrandPrixUseEleRequest")]
  public partial class GrandPrixUseEleRequest : global::ProtoBuf.IExtensible
  {
    public GrandPrixUseEleRequest() {}
    
    private long _fishId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GrandPrixUseEleResponse")]
  public partial class GrandPrixUseEleResponse : global::ProtoBuf.IExtensible
  {
    public GrandPrixUseEleResponse() {}
    
    private long _fishId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fishId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long fishId
    {
      get { return _fishId; }
      set { _fishId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GrandPrixUseBlackRequest")]
  public partial class GrandPrixUseBlackRequest : global::ProtoBuf.IExtensible
  {
    public GrandPrixUseBlackRequest() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GrandPrixUseBlackResponse")]
  public partial class GrandPrixUseBlackResponse : global::ProtoBuf.IExtensible
  {
    public GrandPrixUseBlackResponse() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GrandPrixUseTroRequest")]
  public partial class GrandPrixUseTroRequest : global::ProtoBuf.IExtensible
  {
    public GrandPrixUseTroRequest() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GrandPrixUseTroResponse")]
  public partial class GrandPrixUseTroResponse : global::ProtoBuf.IExtensible
  {
    public GrandPrixUseTroResponse() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GrandPrixUseBitRequest")]
  public partial class GrandPrixUseBitRequest : global::ProtoBuf.IExtensible
  {
    public GrandPrixUseBitRequest() {}
    
    private float _angle = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GrandPrixUseBitResponse")]
  public partial class GrandPrixUseBitResponse : global::ProtoBuf.IExtensible
  {
    public GrandPrixUseBitResponse() {}
    
    private float _angle = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float angle
    {
      get { return _angle; }
      set { _angle = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetUserIpRequest")]
  public partial class GetUserIpRequest : global::ProtoBuf.IExtensible
  {
    public GetUserIpRequest() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _userIp = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userIp
    {
      get { return _userIp; }
      set { _userIp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetUserIpResponse")]
  public partial class GetUserIpResponse : global::ProtoBuf.IExtensible
  {
    public GetUserIpResponse() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _userIp = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userIp
    {
      get { return _userIp; }
      set { _userIp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}