//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/TribeMessage.proto
namespace com.maple.game.osee.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TribeEsTabLishRequest")]
  public partial class TribeEsTabLishRequest : global::ProtoBuf.IExtensible
  {
    public TribeEsTabLishRequest() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _context = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string context
    {
      get { return _context; }
      set { _context = value; }
    }
    private long _vipRestrict = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"vipRestrict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long vipRestrict
    {
      get { return _vipRestrict; }
      set { _vipRestrict = value; }
    }
    private long _levelRestrict = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"levelRestrict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long levelRestrict
    {
      get { return _levelRestrict; }
      set { _levelRestrict = value; }
    }
    private long _verificationRestrict = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"verificationRestrict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long verificationRestrict
    {
      get { return _verificationRestrict; }
      set { _verificationRestrict = value; }
    }
    private string _headUrl = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"headUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headUrl
    {
      get { return _headUrl; }
      set { _headUrl = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TribrEsTabLishResponse")]
  public partial class TribrEsTabLishResponse : global::ProtoBuf.IExtensible
  {
    public TribrEsTabLishResponse() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTribeRequest")]
  public partial class GetTribeRequest : global::ProtoBuf.IExtensible
  {
    public GetTribeRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tribe")]
  public partial class Tribe : global::ProtoBuf.IExtensible
  {
    public Tribe() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userNum = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userNum
    {
      get { return _userNum; }
      set { _userNum = value; }
    }
    private long _realNum = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"realNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long realNum
    {
      get { return _realNum; }
      set { _realNum = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _context = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string context
    {
      get { return _context; }
      set { _context = value; }
    }
    private long _vipRestrict = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"vipRestrict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long vipRestrict
    {
      get { return _vipRestrict; }
      set { _vipRestrict = value; }
    }
    private long _levelRestrict = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"levelRestrict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long levelRestrict
    {
      get { return _levelRestrict; }
      set { _levelRestrict = value; }
    }
    private long _verificationRestrict = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"verificationRestrict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long verificationRestrict
    {
      get { return _verificationRestrict; }
      set { _verificationRestrict = value; }
    }
    private long _fJurisdiction = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"fJurisdiction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long fJurisdiction
    {
      get { return _fJurisdiction; }
      set { _fJurisdiction = value; }
    }
    private long _tJurisdiction = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"tJurisdiction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tJurisdiction
    {
      get { return _tJurisdiction; }
      set { _tJurisdiction = value; }
    }
    private long _sJurisdiction = default(long);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"sJurisdiction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sJurisdiction
    {
      get { return _sJurisdiction; }
      set { _sJurisdiction = value; }
    }
    private long _iJurisdiction = default(long);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"iJurisdiction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long iJurisdiction
    {
      get { return _iJurisdiction; }
      set { _iJurisdiction = value; }
    }
    private long _wJurisdiction = default(long);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"wJurisdiction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long wJurisdiction
    {
      get { return _wJurisdiction; }
      set { _wJurisdiction = value; }
    }
    private long _lJurisdiction = default(long);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"lJurisdiction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lJurisdiction
    {
      get { return _lJurisdiction; }
      set { _lJurisdiction = value; }
    }
    private string _headUrl = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"headUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headUrl
    {
      get { return _headUrl; }
      set { _headUrl = value; }
    }
    private bool _isApply = default(bool);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"isApply", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isApply
    {
      get { return _isApply; }
      set { _isApply = value; }
    }
    private string _slName = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"slName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string slName
    {
      get { return _slName; }
      set { _slName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTribeResponse")]
  public partial class GetTribeResponse : global::ProtoBuf.IExtensible
  {
    public GetTribeResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.Tribe> _tribe = new global::System.Collections.Generic.List<com.maple.game.osee.proto.Tribe>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tribe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.Tribe> tribe
    {
      get { return _tribe; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TribeUser")]
  public partial class TribeUser : global::ProtoBuf.IExtensible
  {
    public TribeUser() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _userName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private long _position = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long position
    {
      get { return _position; }
      set { _position = value; }
    }
    private long _userLevel = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"userLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userLevel
    {
      get { return _userLevel; }
      set { _userLevel = value; }
    }
    private long _money = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long money
    {
      get { return _money; }
      set { _money = value; }
    }
    private long _vipLevel = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"vipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long vipLevel
    {
      get { return _vipLevel; }
      set { _vipLevel = value; }
    }
    private bool _isOnline = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"isOnline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isOnline
    {
      get { return _isOnline; }
      set { _isOnline = value; }
    }
    private long _headIndex = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"headIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long headIndex
    {
      get { return _headIndex; }
      set { _headIndex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTribeAllUser")]
  public partial class GetTribeAllUser : global::ProtoBuf.IExtensible
  {
    public GetTribeAllUser() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTribeAllUserResponse")]
  public partial class GetTribeAllUserResponse : global::ProtoBuf.IExtensible
  {
    public GetTribeAllUserResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeUser> _tribeUser = new global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeUser>();
    [global::ProtoBuf.ProtoMember(3, Name=@"tribeUser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeUser> tribeUser
    {
      get { return _tribeUser; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyTribeRequest")]
  public partial class ApplyTribeRequest : global::ProtoBuf.IExtensible
  {
    public ApplyTribeRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyTripeResponse")]
  public partial class ApplyTripeResponse : global::ProtoBuf.IExtensible
  {
    public ApplyTripeResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DealApplyTribeRequest")]
  public partial class DealApplyTribeRequest : global::ProtoBuf.IExtensible
  {
    public DealApplyTribeRequest() {}
    
    private long _applyId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"applyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long applyId
    {
      get { return _applyId; }
      set { _applyId = value; }
    }
    private long _dealResult = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dealResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long dealResult
    {
      get { return _dealResult; }
      set { _dealResult = value; }
    }
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DealApplyTripeResponse")]
  public partial class DealApplyTripeResponse : global::ProtoBuf.IExtensible
  {
    public DealApplyTripeResponse() {}
    
    private long _applyId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"applyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long applyId
    {
      get { return _applyId; }
      set { _applyId = value; }
    }
    private long _dealResult = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dealResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long dealResult
    {
      get { return _dealResult; }
      set { _dealResult = value; }
    }
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateTribeJurisDictionRequest")]
  public partial class UpdateTribeJurisDictionRequest : global::ProtoBuf.IExtensible
  {
    public UpdateTribeJurisDictionRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _jurisDiction = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"jurisDiction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long jurisDiction
    {
      get { return _jurisDiction; }
      set { _jurisDiction = value; }
    }
    private long _result = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateTribeJurisDictionResponse")]
  public partial class UpdateTribeJurisDictionResponse : global::ProtoBuf.IExtensible
  {
    public UpdateTribeJurisDictionResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _jurisDiction = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"jurisDiction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long jurisDiction
    {
      get { return _jurisDiction; }
      set { _jurisDiction = value; }
    }
    private long _result = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DepositTribeWareHouseRequest")]
  public partial class DepositTribeWareHouseRequest : global::ProtoBuf.IExtensible
  {
    public DepositTribeWareHouseRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private long _itemId = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private long _itemNum = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"itemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemNum
    {
      get { return _itemNum; }
      set { _itemNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DepositTribeWareHouseResponse")]
  public partial class DepositTribeWareHouseResponse : global::ProtoBuf.IExtensible
  {
    public DepositTribeWareHouseResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OutTribeWareHouseRequest")]
  public partial class OutTribeWareHouseRequest : global::ProtoBuf.IExtensible
  {
    public OutTribeWareHouseRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private long _wareId = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"wareId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long wareId
    {
      get { return _wareId; }
      set { _wareId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OutTribeWareHouseResponse")]
  public partial class OutTribeWareHouseResponse : global::ProtoBuf.IExtensible
  {
    public OutTribeWareHouseResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _wareId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"wareId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long wareId
    {
      get { return _wareId; }
      set { _wareId = value; }
    }
    private long _itemId = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private long _itemNum = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"itemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemNum
    {
      get { return _itemNum; }
      set { _itemNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateTribeNameRequest")]
  public partial class UpdateTribeNameRequest : global::ProtoBuf.IExtensible
  {
    public UpdateTribeNameRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateTribeNameResponse")]
  public partial class UpdateTribeNameResponse : global::ProtoBuf.IExtensible
  {
    public UpdateTribeNameResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateTribeContextRequest")]
  public partial class UpdateTribeContextRequest : global::ProtoBuf.IExtensible
  {
    public UpdateTribeContextRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _context = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string context
    {
      get { return _context; }
      set { _context = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateTribeContextResponse")]
  public partial class UpdateTribeContextResponse : global::ProtoBuf.IExtensible
  {
    public UpdateTribeContextResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _context = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string context
    {
      get { return _context; }
      set { _context = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KickOutTribeUserRequest")]
  public partial class KickOutTribeUserRequest : global::ProtoBuf.IExtensible
  {
    public KickOutTribeUserRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KickOutTribeUserResponse")]
  public partial class KickOutTribeUserResponse : global::ProtoBuf.IExtensible
  {
    public KickOutTribeUserResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTribeByIdOrNameRequest")]
  public partial class GetTribeByIdOrNameRequest : global::ProtoBuf.IExtensible
  {
    public GetTribeByIdOrNameRequest() {}
    
    private string _context = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string context
    {
      get { return _context; }
      set { _context = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTribeByIdOrNameResponse")]
  public partial class GetTribeByIdOrNameResponse : global::ProtoBuf.IExtensible
  {
    public GetTribeByIdOrNameResponse() {}
    
    private com.maple.game.osee.proto.Tribe _tribe = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.maple.game.osee.proto.Tribe tribe
    {
      get { return _tribe; }
      set { _tribe = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateTribeLevelRequest")]
  public partial class UpdateTribeLevelRequest : global::ProtoBuf.IExtensible
  {
    public UpdateTribeLevelRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _vipRestrict = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"vipRestrict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long vipRestrict
    {
      get { return _vipRestrict; }
      set { _vipRestrict = value; }
    }
    private long _levelRestrict = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"levelRestrict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long levelRestrict
    {
      get { return _levelRestrict; }
      set { _levelRestrict = value; }
    }
    private long _verificationRestrict = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"verificationRestrict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long verificationRestrict
    {
      get { return _verificationRestrict; }
      set { _verificationRestrict = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UpdateTribeLevelResponse")]
  public partial class UpdateTribeLevelResponse : global::ProtoBuf.IExtensible
  {
    public UpdateTribeLevelResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _vipRestrict = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"vipRestrict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long vipRestrict
    {
      get { return _vipRestrict; }
      set { _vipRestrict = value; }
    }
    private long _levelRestrict = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"levelRestrict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long levelRestrict
    {
      get { return _levelRestrict; }
      set { _levelRestrict = value; }
    }
    private long _verificationRestrict = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"verificationRestrict", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long verificationRestrict
    {
      get { return _verificationRestrict; }
      set { _verificationRestrict = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IsJoinTribeRequest")]
  public partial class IsJoinTribeRequest : global::ProtoBuf.IExtensible
  {
    public IsJoinTribeRequest() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IsJoinTribeResponse")]
  public partial class IsJoinTribeResponse : global::ProtoBuf.IExtensible
  {
    public IsJoinTribeResponse() {}
    
    private readonly global::System.Collections.Generic.List<long> _tribeId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> tribeId
    {
      get { return _tribeId; }
    }
  
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private bool _isJoin = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isJoin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isJoin
    {
      get { return _isJoin; }
      set { _isJoin = value; }
    }
    private bool _isDouble = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isDouble", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isDouble
    {
      get { return _isDouble; }
      set { _isDouble = value; }
    }
    private bool _isAgent = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"isAgent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isAgent
    {
      get { return _isAgent; }
      set { _isAgent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetAllTribeWareHouseRequest")]
  public partial class GetAllTribeWareHouseRequest : global::ProtoBuf.IExtensible
  {
    public GetAllTribeWareHouseRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TribeItem")]
  public partial class TribeItem : global::ProtoBuf.IExtensible
  {
    public TribeItem() {}
    
    private long _itemId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private long _itemNum = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemNum
    {
      get { return _itemNum; }
      set { _itemNum = value; }
    }
    private long _wareHouseId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"wareHouseId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long wareHouseId
    {
      get { return _wareHouseId; }
      set { _wareHouseId = value; }
    }
    private long _isOut = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isOut", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long isOut
    {
      get { return _isOut; }
      set { _isOut = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetAllTribeWareHouseResponse")]
  public partial class GetAllTribeWareHouseResponse : global::ProtoBuf.IExtensible
  {
    public GetAllTribeWareHouseResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeItem> _tribeItem = new global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tribeItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeItem> tribeItem
    {
      get { return _tribeItem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetAllTribeApplyRequest")]
  public partial class GetAllTribeApplyRequest : global::ProtoBuf.IExtensible
  {
    public GetAllTribeApplyRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TribeApply")]
  public partial class TribeApply : global::ProtoBuf.IExtensible
  {
    public TribeApply() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _userName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private long _userLevel = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userLevel
    {
      get { return _userLevel; }
      set { _userLevel = value; }
    }
    private long _vipLevel = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"vipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long vipLevel
    {
      get { return _vipLevel; }
      set { _vipLevel = value; }
    }
    private string _headUrl = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"headUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headUrl
    {
      get { return _headUrl; }
      set { _headUrl = value; }
    }
    private long _applyId = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"applyId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long applyId
    {
      get { return _applyId; }
      set { _applyId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetAllTribeApplyResponse")]
  public partial class GetAllTribeApplyResponse : global::ProtoBuf.IExtensible
  {
    public GetAllTribeApplyResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeApply> _tribeApply = new global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeApply>();
    [global::ProtoBuf.ProtoMember(2, Name=@"tribeApply", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeApply> tribeApply
    {
      get { return _tribeApply; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetOneTribeRequest")]
  public partial class GetOneTribeRequest : global::ProtoBuf.IExtensible
  {
    public GetOneTribeRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetOneTribeResponse")]
  public partial class GetOneTribeResponse : global::ProtoBuf.IExtensible
  {
    public GetOneTribeResponse() {}
    
    private com.maple.game.osee.proto.Tribe _tribe = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribe", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.maple.game.osee.proto.Tribe tribe
    {
      get { return _tribe; }
      set { _tribe = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetTribeUserPositionRequest")]
  public partial class SetTribeUserPositionRequest : global::ProtoBuf.IExtensible
  {
    public SetTribeUserPositionRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _position = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetTribeUserPositionResponse")]
  public partial class SetTribeUserPositionResponse : global::ProtoBuf.IExtensible
  {
    public SetTribeUserPositionResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _position = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetInOrOutRequest")]
  public partial class GetInOrOutRequest : global::ProtoBuf.IExtensible
  {
    public GetInOrOutRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TribeInOrOut")]
  public partial class TribeInOrOut : global::ProtoBuf.IExtensible
  {
    public TribeInOrOut() {}
    
    private long _inUserId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"inUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long inUserId
    {
      get { return _inUserId; }
      set { _inUserId = value; }
    }
    private string _inUserName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"inUserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string inUserName
    {
      get { return _inUserName; }
      set { _inUserName = value; }
    }
    private long _outUserId = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"outUserId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long outUserId
    {
      get { return _outUserId; }
      set { _outUserId = value; }
    }
    private string _outUserName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"outUserName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string outUserName
    {
      get { return _outUserName; }
      set { _outUserName = value; }
    }
    private long _itemId = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private long _itemNum = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"itemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemNum
    {
      get { return _itemNum; }
      set { _itemNum = value; }
    }
    private string _outTime = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"outTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string outTime
    {
      get { return _outTime; }
      set { _outTime = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private long _wareHouseId = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"wareHouseId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long wareHouseId
    {
      get { return _wareHouseId; }
      set { _wareHouseId = value; }
    }
    private long _isOut = default(long);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"isOut", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long isOut
    {
      get { return _isOut; }
      set { _isOut = value; }
    }
    private string _inTime = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"inTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string inTime
    {
      get { return _inTime; }
      set { _inTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetInOrOutResponse")]
  public partial class GetInOrOutResponse : global::ProtoBuf.IExtensible
  {
    public GetInOrOutResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeInOrOut> _tribeInOrOut = new global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeInOrOut>();
    [global::ProtoBuf.ProtoMember(3, Name=@"tribeInOrOut", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeInOrOut> tribeInOrOut
    {
      get { return _tribeInOrOut; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TribeSearchRequest")]
  public partial class TribeSearchRequest : global::ProtoBuf.IExtensible
  {
    public TribeSearchRequest() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _context = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string context
    {
      get { return _context; }
      set { _context = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TribeSearchResponse")]
  public partial class TribeSearchResponse : global::ProtoBuf.IExtensible
  {
    public TribeSearchResponse() {}
    
    private long _tribeId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tribeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long tribeId
    {
      get { return _tribeId; }
      set { _tribeId = value; }
    }
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeItem> _tribeItem = new global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"tribeItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeItem> tribeItem
    {
      get { return _tribeItem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IsTribeGetGiftRequest")]
  public partial class IsTribeGetGiftRequest : global::ProtoBuf.IExtensible
  {
    public IsTribeGetGiftRequest() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IsTribeGetGiftResponse")]
  public partial class IsTribeGetGiftResponse : global::ProtoBuf.IExtensible
  {
    public IsTribeGetGiftResponse() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _isGet = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isGet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long isGet
    {
      get { return _isGet; }
      set { _isGet = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TribeGiftItem")]
  public partial class TribeGiftItem : global::ProtoBuf.IExtensible
  {
    public TribeGiftItem() {}
    
    private int _itemId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private long _itemNum = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long itemNum
    {
      get { return _itemNum; }
      set { _itemNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTribeGiftRequest")]
  public partial class GetTribeGiftRequest : global::ProtoBuf.IExtensible
  {
    public GetTribeGiftRequest() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetTribeGiftResponse")]
  public partial class GetTribeGiftResponse : global::ProtoBuf.IExtensible
  {
    public GetTribeGiftResponse() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private long _isSuccess = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isSuccess", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long isSuccess
    {
      get { return _isSuccess; }
      set { _isSuccess = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeGiftItem> _tribeGiftItem = new global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeGiftItem>();
    [global::ProtoBuf.ProtoMember(4, Name=@"tribeGiftItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.TribeGiftItem> tribeGiftItem
    {
      get { return _tribeGiftItem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}