//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/TtmyFightTenChallengeMessage.proto
// Note: requires additional types generated from: proto/OseeFightTenMessage.proto
namespace com.maple.game.osee.proto.fightten
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeRoomInfoProto")]
  public partial class TenChallengeRoomInfoProto : global::ProtoBuf.IExtensible
  {
    public TenChallengeRoomInfoProto() {}
    
    private int _roomCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private int _roundTotal = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roundTotal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roundTotal
    {
      get { return _roundTotal; }
      set { _roundTotal = value; }
    }
    private int _roundNow = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roundNow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roundNow
    {
      get { return _roundNow; }
      set { _roundNow = value; }
    }
    private long _moneyLimit = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"moneyLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long moneyLimit
    {
      get { return _moneyLimit; }
      set { _moneyLimit = value; }
    }
    private int _feeType = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"feeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int feeType
    {
      get { return _feeType; }
      set { _feeType = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private long _ownerId = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ownerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long ownerId
    {
      get { return _ownerId; }
      set { _ownerId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoomPlayerInfoProto> _roomPlayers = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoomPlayerInfoProto>();
    [global::ProtoBuf.ProtoMember(8, Name=@"roomPlayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoomPlayerInfoProto> roomPlayers
    {
      get { return _roomPlayers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeRankingProto")]
  public partial class TenChallengeRankingProto : global::ProtoBuf.IExtensible
  {
    public TenChallengeRankingProto() {}
    
    private long _userId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _nickname = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private int _headIndex = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int headIndex
    {
      get { return _headIndex; }
      set { _headIndex = value; }
    }
    private string _headUrl = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"headUrl", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headUrl
    {
      get { return _headUrl; }
      set { _headUrl = value; }
    }
    private long _score = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeExchangeTimeRequest")]
  public partial class TenChallengeExchangeTimeRequest : global::ProtoBuf.IExtensible
  {
    public TenChallengeExchangeTimeRequest() {}
    
    private int _diamondNum = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"diamondNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int diamondNum
    {
      get { return _diamondNum; }
      set { _diamondNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeExchangeTimeResponse")]
  public partial class TenChallengeExchangeTimeResponse : global::ProtoBuf.IExtensible
  {
    public TenChallengeExchangeTimeResponse() {}
    
    private int _times = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeRoomListRequest")]
  public partial class TenChallengeRoomListRequest : global::ProtoBuf.IExtensible
  {
    public TenChallengeRoomListRequest() {}
    
    private int _pageNo = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pageNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pageNo
    {
      get { return _pageNo; }
      set { _pageNo = value; }
    }
    private int _pageSize = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pageSize", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pageSize
    {
      get { return _pageSize; }
      set { _pageSize = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeRoomListResponse")]
  public partial class TenChallengeRoomListResponse : global::ProtoBuf.IExtensible
  {
    public TenChallengeRoomListResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenChallengeRoomInfoProto> _roomList = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenChallengeRoomInfoProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"roomList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenChallengeRoomInfoProto> roomList
    {
      get { return _roomList; }
    }
  
    private int _pageNo = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pageNo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int pageNo
    {
      get { return _pageNo; }
      set { _pageNo = value; }
    }
    private int _totalCount = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"totalCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalCount
    {
      get { return _totalCount; }
      set { _totalCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeCreateRoomRequest")]
  public partial class TenChallengeCreateRoomRequest : global::ProtoBuf.IExtensible
  {
    public TenChallengeCreateRoomRequest() {}
    
    private int _moneyLimitIndex = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"moneyLimitIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moneyLimitIndex
    {
      get { return _moneyLimitIndex; }
      set { _moneyLimitIndex = value; }
    }
    private int _feeType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"feeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int feeType
    {
      get { return _feeType; }
      set { _feeType = value; }
    }
    private int _roundIndex = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roundIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roundIndex
    {
      get { return _roundIndex; }
      set { _roundIndex = value; }
    }
    private bool _privateRoom = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"privateRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool privateRoom
    {
      get { return _privateRoom; }
      set { _privateRoom = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeMatchRequest")]
  public partial class TenChallengeMatchRequest : global::ProtoBuf.IExtensible
  {
    public TenChallengeMatchRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeMatchResponse")]
  public partial class TenChallengeMatchResponse : global::ProtoBuf.IExtensible
  {
    public TenChallengeMatchResponse() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _info = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string info
    {
      get { return _info; }
      set { _info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeCancelMatchRequest")]
  public partial class TenChallengeCancelMatchRequest : global::ProtoBuf.IExtensible
  {
    public TenChallengeCancelMatchRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeCancelMatchResponse")]
  public partial class TenChallengeCancelMatchResponse : global::ProtoBuf.IExtensible
  {
    public TenChallengeCancelMatchResponse() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeJoinRoomRequest")]
  public partial class TenChallengeJoinRoomRequest : global::ProtoBuf.IExtensible
  {
    public TenChallengeJoinRoomRequest() {}
    
    private int _roomCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeJoinRoomResponse")]
  public partial class TenChallengeJoinRoomResponse : global::ProtoBuf.IExtensible
  {
    public TenChallengeJoinRoomResponse() {}
    
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private string _msg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeRoomInfoResponse")]
  public partial class TenChallengeRoomInfoResponse : global::ProtoBuf.IExtensible
  {
    public TenChallengeRoomInfoResponse() {}
    
    private com.maple.game.osee.proto.fightten.TenChallengeRoomInfoProto _roomInfo = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.maple.game.osee.proto.fightten.TenChallengeRoomInfoProto roomInfo
    {
      get { return _roomInfo; }
      set { _roomInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeKickPlayerRequest")]
  public partial class TenChallengeKickPlayerRequest : global::ProtoBuf.IExtensible
  {
    public TenChallengeKickPlayerRequest() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeReconnectResponse")]
  public partial class TenChallengeReconnectResponse : global::ProtoBuf.IExtensible
  {
    public TenChallengeReconnectResponse() {}
    
    private int _roomCode = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private long _maxBetMoney = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"maxBetMoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long maxBetMoney
    {
      get { return _maxBetMoney; }
      set { _maxBetMoney = value; }
    }
    private int _roomState = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomState
    {
      get { return _roomState; }
      set { _roomState = value; }
    }
    private int _stateRestTime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stateRestTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stateRestTime
    {
      get { return _stateRestTime; }
      set { _stateRestTime = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _readyPlayers = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(5, Name=@"readyPlayers", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> readyPlayers
    {
      get { return _readyPlayers; }
    }
  
    private int _seat = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"seat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int seat
    {
      get { return _seat; }
      set { _seat = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFightBankerProto> _fightedBankerProto = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFightBankerProto>();
    [global::ProtoBuf.ProtoMember(8, Name=@"fightedBankerProto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFightBankerProto> fightedBankerProto
    {
      get { return _fightedBankerProto; }
    }
  
    private long _bankerId = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"bankerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long bankerId
    {
      get { return _bankerId; }
      set { _bankerId = value; }
    }
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFightBankerProto> _fightBankerProto = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFightBankerProto>();
    [global::ProtoBuf.ProtoMember(10, Name=@"fightBankerProto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenFightBankerProto> fightBankerProto
    {
      get { return _fightBankerProto; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _aniPlayerId = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(11, Name=@"aniPlayerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> aniPlayerId
    {
      get { return _aniPlayerId; }
    }
  
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenBetMoneyProto> _betMoneyProto = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenBetMoneyProto>();
    [global::ProtoBuf.ProtoMember(12, Name=@"betMoneyProto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenBetMoneyProto> betMoneyProto
    {
      get { return _betMoneyProto; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _betMoneyList = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(13, Name=@"betMoneyList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> betMoneyList
    {
      get { return _betMoneyList; }
    }
  
    private int _lastCard = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"lastCard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lastCard
    {
      get { return _lastCard; }
      set { _lastCard = value; }
    }
    private readonly global::System.Collections.Generic.List<long> _seeOrRubCardPlayer = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(15, Name=@"seeOrRubCardPlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<long> seeOrRubCardPlayer
    {
      get { return _seeOrRubCardPlayer; }
    }
  
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoundOverPlayerDataProto> _roundOverProto = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoundOverPlayerDataProto>();
    [global::ProtoBuf.ProtoMember(16, Name=@"roundOverProto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenRoundOverPlayerDataProto> roundOverProto
    {
      get { return _roundOverProto; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeRestTimesRequest")]
  public partial class TenChallengeRestTimesRequest : global::ProtoBuf.IExtensible
  {
    public TenChallengeRestTimesRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeRestTimeResponse")]
  public partial class TenChallengeRestTimeResponse : global::ProtoBuf.IExtensible
  {
    public TenChallengeRestTimeResponse() {}
    
    private long _times = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long times
    {
      get { return _times; }
      set { _times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeRankingListRequest")]
  public partial class TenChallengeRankingListRequest : global::ProtoBuf.IExtensible
  {
    public TenChallengeRankingListRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeRankingListResponse")]
  public partial class TenChallengeRankingListResponse : global::ProtoBuf.IExtensible
  {
    public TenChallengeRankingListResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenChallengeRankingProto> _ranking = new global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenChallengeRankingProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.fightten.TenChallengeRankingProto> ranking
    {
      get { return _ranking; }
    }
  
    private int _myRanking = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"myRanking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int myRanking
    {
      get { return _myRanking; }
      set { _myRanking = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeLeaveRoomRequest")]
  public partial class TenChallengeLeaveRoomRequest : global::ProtoBuf.IExtensible
  {
    public TenChallengeLeaveRoomRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TenChallengeLeaveRoomResponse")]
  public partial class TenChallengeLeaveRoomResponse : global::ProtoBuf.IExtensible
  {
    public TenChallengeLeaveRoomResponse() {}
    
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}