//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/TtmyGoldenPig.proto
// Note: requires additional types generated from: proto/OseePublicData.proto
namespace com.maple.game.osee.proto.goldenpig
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoldenPigBreakRequest")]
  public partial class GoldenPigBreakRequest : global::ProtoBuf.IExtensible
  {
    public GoldenPigBreakRequest() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoldenPigBreakResponse")]
  public partial class GoldenPigBreakResponse : global::ProtoBuf.IExtensible
  {
    public GoldenPigBreakResponse() {}
    
    private readonly global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto> _items = new global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.maple.game.osee.proto.ItemDataProto> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoldenPigFreeTimesRequest")]
  public partial class GoldenPigFreeTimesRequest : global::ProtoBuf.IExtensible
  {
    public GoldenPigFreeTimesRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoldenPigFreeTimesResponse")]
  public partial class GoldenPigFreeTimesResponse : global::ProtoBuf.IExtensible
  {
    public GoldenPigFreeTimesResponse() {}
    
    private int _times = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoldenPigHitLimitRequest")]
  public partial class GoldenPigHitLimitRequest : global::ProtoBuf.IExtensible
  {
    public GoldenPigHitLimitRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GoldenPigHitLimitResponse")]
  public partial class GoldenPigHitLimitResponse : global::ProtoBuf.IExtensible
  {
    public GoldenPigHitLimitResponse() {}
    
    private int _restLimit = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"restLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int restLimit
    {
      get { return _restLimit; }
      set { _restLimit = value; }
    }
    private int _totalLimit = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"totalLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalLimit
    {
      get { return _totalLimit; }
      set { _totalLimit = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}