// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LaBa.proto

package com.maple.game.osee.proto;

public final class LaBa {
  private LaBa() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LaBaSpinRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.maple.game.osee.proto.LaBaSpinRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 spin_multiple = 1;</code>
     *
     * <pre>
     * 下注倍数
     * </pre>
     */
    boolean hasSpinMultiple();
    /**
     * <code>required int32 spin_multiple = 1;</code>
     *
     * <pre>
     * 下注倍数
     * </pre>
     */
    int getSpinMultiple();
  }
  /**
   * Protobuf type {@code com.maple.game.osee.proto.LaBaSpinRequest}
   *
   * <pre>
   * C_S_LA_BA_SPIN_REQUEST = 0x10040030; // 拉霸旋转请求
   * </pre>
   */
  public static final class LaBaSpinRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.maple.game.osee.proto.LaBaSpinRequest)
      LaBaSpinRequestOrBuilder {
    // Use LaBaSpinRequest.newBuilder() to construct.
    private LaBaSpinRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LaBaSpinRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LaBaSpinRequest defaultInstance;
    public static LaBaSpinRequest getDefaultInstance() {
      return defaultInstance;
    }

    public LaBaSpinRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LaBaSpinRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              spinMultiple_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.maple.game.osee.proto.LaBa.internal_static_com_maple_game_osee_proto_LaBaSpinRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.maple.game.osee.proto.LaBa.internal_static_com_maple_game_osee_proto_LaBaSpinRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.maple.game.osee.proto.LaBa.LaBaSpinRequest.class, com.maple.game.osee.proto.LaBa.LaBaSpinRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<LaBaSpinRequest> PARSER =
        new com.google.protobuf.AbstractParser<LaBaSpinRequest>() {
      public LaBaSpinRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LaBaSpinRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LaBaSpinRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SPIN_MULTIPLE_FIELD_NUMBER = 1;
    private int spinMultiple_;
    /**
     * <code>required int32 spin_multiple = 1;</code>
     *
     * <pre>
     * 下注倍数
     * </pre>
     */
    public boolean hasSpinMultiple() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 spin_multiple = 1;</code>
     *
     * <pre>
     * 下注倍数
     * </pre>
     */
    public int getSpinMultiple() {
      return spinMultiple_;
    }

    private void initFields() {
      spinMultiple_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSpinMultiple()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, spinMultiple_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, spinMultiple_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.maple.game.osee.proto.LaBa.LaBaSpinRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.maple.game.osee.proto.LaBa.LaBaSpinRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.maple.game.osee.proto.LaBaSpinRequest}
     *
     * <pre>
     * C_S_LA_BA_SPIN_REQUEST = 0x10040030; // 拉霸旋转请求
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.maple.game.osee.proto.LaBaSpinRequest)
        com.maple.game.osee.proto.LaBa.LaBaSpinRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.maple.game.osee.proto.LaBa.internal_static_com_maple_game_osee_proto_LaBaSpinRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.maple.game.osee.proto.LaBa.internal_static_com_maple_game_osee_proto_LaBaSpinRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.maple.game.osee.proto.LaBa.LaBaSpinRequest.class, com.maple.game.osee.proto.LaBa.LaBaSpinRequest.Builder.class);
      }

      // Construct using com.maple.game.osee.proto.LaBa.LaBaSpinRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        spinMultiple_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.maple.game.osee.proto.LaBa.internal_static_com_maple_game_osee_proto_LaBaSpinRequest_descriptor;
      }

      public com.maple.game.osee.proto.LaBa.LaBaSpinRequest getDefaultInstanceForType() {
        return com.maple.game.osee.proto.LaBa.LaBaSpinRequest.getDefaultInstance();
      }

      public com.maple.game.osee.proto.LaBa.LaBaSpinRequest build() {
        com.maple.game.osee.proto.LaBa.LaBaSpinRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.maple.game.osee.proto.LaBa.LaBaSpinRequest buildPartial() {
        com.maple.game.osee.proto.LaBa.LaBaSpinRequest result = new com.maple.game.osee.proto.LaBa.LaBaSpinRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.spinMultiple_ = spinMultiple_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.maple.game.osee.proto.LaBa.LaBaSpinRequest) {
          return mergeFrom((com.maple.game.osee.proto.LaBa.LaBaSpinRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.maple.game.osee.proto.LaBa.LaBaSpinRequest other) {
        if (other == com.maple.game.osee.proto.LaBa.LaBaSpinRequest.getDefaultInstance()) return this;
        if (other.hasSpinMultiple()) {
          setSpinMultiple(other.getSpinMultiple());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSpinMultiple()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.maple.game.osee.proto.LaBa.LaBaSpinRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.maple.game.osee.proto.LaBa.LaBaSpinRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int spinMultiple_ ;
      /**
       * <code>required int32 spin_multiple = 1;</code>
       *
       * <pre>
       * 下注倍数
       * </pre>
       */
      public boolean hasSpinMultiple() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 spin_multiple = 1;</code>
       *
       * <pre>
       * 下注倍数
       * </pre>
       */
      public int getSpinMultiple() {
        return spinMultiple_;
      }
      /**
       * <code>required int32 spin_multiple = 1;</code>
       *
       * <pre>
       * 下注倍数
       * </pre>
       */
      public Builder setSpinMultiple(int value) {
        bitField0_ |= 0x00000001;
        spinMultiple_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 spin_multiple = 1;</code>
       *
       * <pre>
       * 下注倍数
       * </pre>
       */
      public Builder clearSpinMultiple() {
        bitField0_ = (bitField0_ & ~0x00000001);
        spinMultiple_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.maple.game.osee.proto.LaBaSpinRequest)
    }

    static {
      defaultInstance = new LaBaSpinRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.maple.game.osee.proto.LaBaSpinRequest)
  }

  public interface LaBaSpinResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.maple.game.osee.proto.LaBaSpinResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 pattern_list = 1;</code>
     *
     * <pre>
     * 图案集合，展示用
     * </pre>
     */
    java.util.List<java.lang.Integer> getPatternListList();
    /**
     * <code>repeated int32 pattern_list = 1;</code>
     *
     * <pre>
     * 图案集合，展示用
     * </pre>
     */
    int getPatternListCount();
    /**
     * <code>repeated int32 pattern_list = 1;</code>
     *
     * <pre>
     * 图案集合，展示用
     * </pre>
     */
    int getPatternList(int index);

    /**
     * <code>repeated int32 win_pattern_index_list = 2;</code>
     *
     * <pre>
     * 中奖的图案下标，集合
     * </pre>
     */
    java.util.List<java.lang.Integer> getWinPatternIndexListList();
    /**
     * <code>repeated int32 win_pattern_index_list = 2;</code>
     *
     * <pre>
     * 中奖的图案下标，集合
     * </pre>
     */
    int getWinPatternIndexListCount();
    /**
     * <code>repeated int32 win_pattern_index_list = 2;</code>
     *
     * <pre>
     * 中奖的图案下标，集合
     * </pre>
     */
    int getWinPatternIndexList(int index);

    /**
     * <code>required int64 win_money = 3;</code>
     *
     * <pre>
     * 赢的钱
     * </pre>
     */
    boolean hasWinMoney();
    /**
     * <code>required int64 win_money = 3;</code>
     *
     * <pre>
     * 赢的钱
     * </pre>
     */
    long getWinMoney();

    /**
     * <code>required int64 win_multiple = 4;</code>
     *
     * <pre>
     * 赢的倍数
     * </pre>
     */
    boolean hasWinMultiple();
    /**
     * <code>required int64 win_multiple = 4;</code>
     *
     * <pre>
     * 赢的倍数
     * </pre>
     */
    long getWinMultiple();
  }
  /**
   * Protobuf type {@code com.maple.game.osee.proto.LaBaSpinResponse}
   *
   * <pre>
   * S_C_LA_BA_SPIN_RESPONSE = 0x20040030; // 拉霸旋转响应
   * </pre>
   */
  public static final class LaBaSpinResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.maple.game.osee.proto.LaBaSpinResponse)
      LaBaSpinResponseOrBuilder {
    // Use LaBaSpinResponse.newBuilder() to construct.
    private LaBaSpinResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LaBaSpinResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LaBaSpinResponse defaultInstance;
    public static LaBaSpinResponse getDefaultInstance() {
      return defaultInstance;
    }

    public LaBaSpinResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LaBaSpinResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                patternList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              patternList_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                patternList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                patternList_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                winPatternIndexList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              winPatternIndexList_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                winPatternIndexList_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                winPatternIndexList_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000001;
              winMoney_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              winMultiple_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          patternList_ = java.util.Collections.unmodifiableList(patternList_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          winPatternIndexList_ = java.util.Collections.unmodifiableList(winPatternIndexList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.maple.game.osee.proto.LaBa.internal_static_com_maple_game_osee_proto_LaBaSpinResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.maple.game.osee.proto.LaBa.internal_static_com_maple_game_osee_proto_LaBaSpinResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.maple.game.osee.proto.LaBa.LaBaSpinResponse.class, com.maple.game.osee.proto.LaBa.LaBaSpinResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<LaBaSpinResponse> PARSER =
        new com.google.protobuf.AbstractParser<LaBaSpinResponse>() {
      public LaBaSpinResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LaBaSpinResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LaBaSpinResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PATTERN_LIST_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> patternList_;
    /**
     * <code>repeated int32 pattern_list = 1;</code>
     *
     * <pre>
     * 图案集合，展示用
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getPatternListList() {
      return patternList_;
    }
    /**
     * <code>repeated int32 pattern_list = 1;</code>
     *
     * <pre>
     * 图案集合，展示用
     * </pre>
     */
    public int getPatternListCount() {
      return patternList_.size();
    }
    /**
     * <code>repeated int32 pattern_list = 1;</code>
     *
     * <pre>
     * 图案集合，展示用
     * </pre>
     */
    public int getPatternList(int index) {
      return patternList_.get(index);
    }

    public static final int WIN_PATTERN_INDEX_LIST_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> winPatternIndexList_;
    /**
     * <code>repeated int32 win_pattern_index_list = 2;</code>
     *
     * <pre>
     * 中奖的图案下标，集合
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getWinPatternIndexListList() {
      return winPatternIndexList_;
    }
    /**
     * <code>repeated int32 win_pattern_index_list = 2;</code>
     *
     * <pre>
     * 中奖的图案下标，集合
     * </pre>
     */
    public int getWinPatternIndexListCount() {
      return winPatternIndexList_.size();
    }
    /**
     * <code>repeated int32 win_pattern_index_list = 2;</code>
     *
     * <pre>
     * 中奖的图案下标，集合
     * </pre>
     */
    public int getWinPatternIndexList(int index) {
      return winPatternIndexList_.get(index);
    }

    public static final int WIN_MONEY_FIELD_NUMBER = 3;
    private long winMoney_;
    /**
     * <code>required int64 win_money = 3;</code>
     *
     * <pre>
     * 赢的钱
     * </pre>
     */
    public boolean hasWinMoney() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 win_money = 3;</code>
     *
     * <pre>
     * 赢的钱
     * </pre>
     */
    public long getWinMoney() {
      return winMoney_;
    }

    public static final int WIN_MULTIPLE_FIELD_NUMBER = 4;
    private long winMultiple_;
    /**
     * <code>required int64 win_multiple = 4;</code>
     *
     * <pre>
     * 赢的倍数
     * </pre>
     */
    public boolean hasWinMultiple() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 win_multiple = 4;</code>
     *
     * <pre>
     * 赢的倍数
     * </pre>
     */
    public long getWinMultiple() {
      return winMultiple_;
    }

    private void initFields() {
      patternList_ = java.util.Collections.emptyList();
      winPatternIndexList_ = java.util.Collections.emptyList();
      winMoney_ = 0L;
      winMultiple_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasWinMoney()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWinMultiple()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < patternList_.size(); i++) {
        output.writeInt32(1, patternList_.get(i));
      }
      for (int i = 0; i < winPatternIndexList_.size(); i++) {
        output.writeInt32(2, winPatternIndexList_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(3, winMoney_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(4, winMultiple_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < patternList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(patternList_.get(i));
        }
        size += dataSize;
        size += 1 * getPatternListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < winPatternIndexList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(winPatternIndexList_.get(i));
        }
        size += dataSize;
        size += 1 * getWinPatternIndexListList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, winMoney_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, winMultiple_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.maple.game.osee.proto.LaBa.LaBaSpinResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.maple.game.osee.proto.LaBa.LaBaSpinResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.maple.game.osee.proto.LaBa.LaBaSpinResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.maple.game.osee.proto.LaBaSpinResponse}
     *
     * <pre>
     * S_C_LA_BA_SPIN_RESPONSE = 0x20040030; // 拉霸旋转响应
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.maple.game.osee.proto.LaBaSpinResponse)
        com.maple.game.osee.proto.LaBa.LaBaSpinResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.maple.game.osee.proto.LaBa.internal_static_com_maple_game_osee_proto_LaBaSpinResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.maple.game.osee.proto.LaBa.internal_static_com_maple_game_osee_proto_LaBaSpinResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.maple.game.osee.proto.LaBa.LaBaSpinResponse.class, com.maple.game.osee.proto.LaBa.LaBaSpinResponse.Builder.class);
      }

      // Construct using com.maple.game.osee.proto.LaBa.LaBaSpinResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        patternList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        winPatternIndexList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        winMoney_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        winMultiple_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.maple.game.osee.proto.LaBa.internal_static_com_maple_game_osee_proto_LaBaSpinResponse_descriptor;
      }

      public com.maple.game.osee.proto.LaBa.LaBaSpinResponse getDefaultInstanceForType() {
        return com.maple.game.osee.proto.LaBa.LaBaSpinResponse.getDefaultInstance();
      }

      public com.maple.game.osee.proto.LaBa.LaBaSpinResponse build() {
        com.maple.game.osee.proto.LaBa.LaBaSpinResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.maple.game.osee.proto.LaBa.LaBaSpinResponse buildPartial() {
        com.maple.game.osee.proto.LaBa.LaBaSpinResponse result = new com.maple.game.osee.proto.LaBa.LaBaSpinResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          patternList_ = java.util.Collections.unmodifiableList(patternList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.patternList_ = patternList_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          winPatternIndexList_ = java.util.Collections.unmodifiableList(winPatternIndexList_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.winPatternIndexList_ = winPatternIndexList_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000001;
        }
        result.winMoney_ = winMoney_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000002;
        }
        result.winMultiple_ = winMultiple_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.maple.game.osee.proto.LaBa.LaBaSpinResponse) {
          return mergeFrom((com.maple.game.osee.proto.LaBa.LaBaSpinResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.maple.game.osee.proto.LaBa.LaBaSpinResponse other) {
        if (other == com.maple.game.osee.proto.LaBa.LaBaSpinResponse.getDefaultInstance()) return this;
        if (!other.patternList_.isEmpty()) {
          if (patternList_.isEmpty()) {
            patternList_ = other.patternList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePatternListIsMutable();
            patternList_.addAll(other.patternList_);
          }
          onChanged();
        }
        if (!other.winPatternIndexList_.isEmpty()) {
          if (winPatternIndexList_.isEmpty()) {
            winPatternIndexList_ = other.winPatternIndexList_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureWinPatternIndexListIsMutable();
            winPatternIndexList_.addAll(other.winPatternIndexList_);
          }
          onChanged();
        }
        if (other.hasWinMoney()) {
          setWinMoney(other.getWinMoney());
        }
        if (other.hasWinMultiple()) {
          setWinMultiple(other.getWinMultiple());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWinMoney()) {
          
          return false;
        }
        if (!hasWinMultiple()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.maple.game.osee.proto.LaBa.LaBaSpinResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.maple.game.osee.proto.LaBa.LaBaSpinResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> patternList_ = java.util.Collections.emptyList();
      private void ensurePatternListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          patternList_ = new java.util.ArrayList<java.lang.Integer>(patternList_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 pattern_list = 1;</code>
       *
       * <pre>
       * 图案集合，展示用
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getPatternListList() {
        return java.util.Collections.unmodifiableList(patternList_);
      }
      /**
       * <code>repeated int32 pattern_list = 1;</code>
       *
       * <pre>
       * 图案集合，展示用
       * </pre>
       */
      public int getPatternListCount() {
        return patternList_.size();
      }
      /**
       * <code>repeated int32 pattern_list = 1;</code>
       *
       * <pre>
       * 图案集合，展示用
       * </pre>
       */
      public int getPatternList(int index) {
        return patternList_.get(index);
      }
      /**
       * <code>repeated int32 pattern_list = 1;</code>
       *
       * <pre>
       * 图案集合，展示用
       * </pre>
       */
      public Builder setPatternList(
          int index, int value) {
        ensurePatternListIsMutable();
        patternList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 pattern_list = 1;</code>
       *
       * <pre>
       * 图案集合，展示用
       * </pre>
       */
      public Builder addPatternList(int value) {
        ensurePatternListIsMutable();
        patternList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 pattern_list = 1;</code>
       *
       * <pre>
       * 图案集合，展示用
       * </pre>
       */
      public Builder addAllPatternList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePatternListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, patternList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 pattern_list = 1;</code>
       *
       * <pre>
       * 图案集合，展示用
       * </pre>
       */
      public Builder clearPatternList() {
        patternList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> winPatternIndexList_ = java.util.Collections.emptyList();
      private void ensureWinPatternIndexListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          winPatternIndexList_ = new java.util.ArrayList<java.lang.Integer>(winPatternIndexList_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 win_pattern_index_list = 2;</code>
       *
       * <pre>
       * 中奖的图案下标，集合
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getWinPatternIndexListList() {
        return java.util.Collections.unmodifiableList(winPatternIndexList_);
      }
      /**
       * <code>repeated int32 win_pattern_index_list = 2;</code>
       *
       * <pre>
       * 中奖的图案下标，集合
       * </pre>
       */
      public int getWinPatternIndexListCount() {
        return winPatternIndexList_.size();
      }
      /**
       * <code>repeated int32 win_pattern_index_list = 2;</code>
       *
       * <pre>
       * 中奖的图案下标，集合
       * </pre>
       */
      public int getWinPatternIndexList(int index) {
        return winPatternIndexList_.get(index);
      }
      /**
       * <code>repeated int32 win_pattern_index_list = 2;</code>
       *
       * <pre>
       * 中奖的图案下标，集合
       * </pre>
       */
      public Builder setWinPatternIndexList(
          int index, int value) {
        ensureWinPatternIndexListIsMutable();
        winPatternIndexList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 win_pattern_index_list = 2;</code>
       *
       * <pre>
       * 中奖的图案下标，集合
       * </pre>
       */
      public Builder addWinPatternIndexList(int value) {
        ensureWinPatternIndexListIsMutable();
        winPatternIndexList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 win_pattern_index_list = 2;</code>
       *
       * <pre>
       * 中奖的图案下标，集合
       * </pre>
       */
      public Builder addAllWinPatternIndexList(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureWinPatternIndexListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, winPatternIndexList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 win_pattern_index_list = 2;</code>
       *
       * <pre>
       * 中奖的图案下标，集合
       * </pre>
       */
      public Builder clearWinPatternIndexList() {
        winPatternIndexList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private long winMoney_ ;
      /**
       * <code>required int64 win_money = 3;</code>
       *
       * <pre>
       * 赢的钱
       * </pre>
       */
      public boolean hasWinMoney() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 win_money = 3;</code>
       *
       * <pre>
       * 赢的钱
       * </pre>
       */
      public long getWinMoney() {
        return winMoney_;
      }
      /**
       * <code>required int64 win_money = 3;</code>
       *
       * <pre>
       * 赢的钱
       * </pre>
       */
      public Builder setWinMoney(long value) {
        bitField0_ |= 0x00000004;
        winMoney_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 win_money = 3;</code>
       *
       * <pre>
       * 赢的钱
       * </pre>
       */
      public Builder clearWinMoney() {
        bitField0_ = (bitField0_ & ~0x00000004);
        winMoney_ = 0L;
        onChanged();
        return this;
      }

      private long winMultiple_ ;
      /**
       * <code>required int64 win_multiple = 4;</code>
       *
       * <pre>
       * 赢的倍数
       * </pre>
       */
      public boolean hasWinMultiple() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 win_multiple = 4;</code>
       *
       * <pre>
       * 赢的倍数
       * </pre>
       */
      public long getWinMultiple() {
        return winMultiple_;
      }
      /**
       * <code>required int64 win_multiple = 4;</code>
       *
       * <pre>
       * 赢的倍数
       * </pre>
       */
      public Builder setWinMultiple(long value) {
        bitField0_ |= 0x00000008;
        winMultiple_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 win_multiple = 4;</code>
       *
       * <pre>
       * 赢的倍数
       * </pre>
       */
      public Builder clearWinMultiple() {
        bitField0_ = (bitField0_ & ~0x00000008);
        winMultiple_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.maple.game.osee.proto.LaBaSpinResponse)
    }

    static {
      defaultInstance = new LaBaSpinResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.maple.game.osee.proto.LaBaSpinResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_maple_game_osee_proto_LaBaSpinRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_maple_game_osee_proto_LaBaSpinRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_maple_game_osee_proto_LaBaSpinResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_maple_game_osee_proto_LaBaSpinResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nLaBa.proto\022\031com.maple.game.osee.proto\"" +
      "(\n\017LaBaSpinRequest\022\025\n\rspin_multiple\030\001 \002(" +
      "\005\"q\n\020LaBaSpinResponse\022\024\n\014pattern_list\030\001 " +
      "\003(\005\022\036\n\026win_pattern_index_list\030\002 \003(\005\022\021\n\tw" +
      "in_money\030\003 \002(\003\022\024\n\014win_multiple\030\004 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_maple_game_osee_proto_LaBaSpinRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_maple_game_osee_proto_LaBaSpinRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_maple_game_osee_proto_LaBaSpinRequest_descriptor,
        new java.lang.String[] { "SpinMultiple", });
    internal_static_com_maple_game_osee_proto_LaBaSpinResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_maple_game_osee_proto_LaBaSpinResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_maple_game_osee_proto_LaBaSpinResponse_descriptor,
        new java.lang.String[] { "PatternList", "WinPatternIndexList", "WinMoney", "WinMultiple", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
